### PR TITLE
don't apply additional filters to the result that is returned from the remote endpoint

### PR DESCRIPTION
**Pull request by jochenberger**
See #1352, #1214, #664

### CODE REVIEW

**Comment by jochenberger** [comment]
Not sure what to do with those test. I'd say they should be removed, because they don't make sense anymore.

**Comment by agirton** [comment]
Hi @jochenberger thank you for your contribution. Instead of removing them the default could be false. This way if users still want this behavior they can opt in. This feels like a breaking change though. Let me give this a bit more thought.

**Comment by agirton** [comment]
Hi @jochenberger removing this behavior doesn't seem the right thing to do so can you update the PR to just default to false? We will need to communicate this in the docs as well.

**Comment by jochenberger** [comment]
I updated the PR. Any suggestions on how the docs should be updated? I assume it should be mentioned in the "Async options" section.

**Comment by JedWatson** [comment]
Hey @jochenberger sorry for the runaround on this one - I'm not inclined to change the default behaviour before the next major version, as it's a big breaking change for anyone using the component and expecting the current behaviour.

Going to close this (aiming to get all PRs merged or closed) but will definitely consider less opinionated defaults in the next major version.

Thanks!

**Pull request closed without merging**
