### PR TITLE
Drop-down closes although closeOnSelect is set to false  (#3443)

### PR DESCRIPTION
**Pull request by NiceGuyNimni**
Quick fix for issue #3443

### CODE REVIEW

**Comment by NiceGuyNimni** [comment]
This one is a quick fix for the issue.
If clicked on option element and the closeOnSelect is not set to 'true' we return without closing the drop down

**Comment by ZLester** [comment]
Any update on this one? Would be awesome to get this fixed in 1.x

**Comment by NiceGuyNimni** [comment]
Don't know how to get @JedWatson to merge my fix so other people get have a fixed version :(

**Comment by ZLester** [comment]
@gwyneplaine might be a better point of contact

**Comment by JonathanMerklin** [comment]
Running into the same thing in a legacy project. It would be really great to have this in 1.x.

**Comment by bladey** [comment]
Hi @NiceGuyNimni,

Thanks for this pull request.

If you feel this pull request is still relevant for the latest version (v3), let us know and we'll determine if it should be reopened and brought up to date to get it merged.

In an effort to sustain the `react-select` project going forward, we're cleaning up and closing old and unmergeable pull requests that relate to old versions of `react-select`.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version v3 and beyond.

**Pull request closed without merging**
