### PR TITLE
Fix creatable not supporting Int values and value accessors #2955 #2953

### LINKED ISSUE #2955: [V2] Creatable crashes with values without `toLowerCase` in prototype
This issue is very similar to https://github.com/JedWatson/react-select/issues/2953 and the same lines are affected here.

When using Creatable you're limited to only using values who's type's prototype has the toLowerCase method which causes the entire component/application to crash if you're using int's for values which i can only imagine im not the only one doing this.

Example: https://codesandbox.io/s/18w2ymppql

Reproduce steps:
1. visit example
2. open dropdown
3. type anything
4. watch the fireworks

### PR DESCRIPTION
**Pull request by th3fallen**
Resolves #2955 and #2953

### CODE REVIEW

**Comment by akre54** [comment]
Just saw this PR. Unfortunately this doesn't fix #2953, as that will still use the default `option.label` and `option.value` instead of the custom fields. I created #2964 for that use case.

I'm wondering for this bug if we can just check for the presence of `toLowerCase` instead of casting to a string? Since '2345' doesn't have a lowercase representation, and will allow for other things like passing objects as values.

The alternative is the library can expose `compareOption` as an overridable option instead of needing to replace the entire `isValidNewOption` logic.

**Comment by th3fallen** [comment]
i thought about checking their types but that seemed like a lot of overhead and i wasnt super familiar with the codebase so i didnt want to get too far down a rabbit hole

**Comment by akre54** [comment]
I would do 

```
(option.value.toLowerCase ? option.value.toLowerCase() : option.value === candidate) ||
(option.label.toLowerCase ? option.label.toLowerCase() : option.label === candidate)
```

This only solves this bug. To solve both #2955 and #2953 you should save value and label to temp variables:

```
const value = getOptionValue(option);
const label = getOptionLabel(option);
(value.toLowerCase ? value.toLowerCase() : value) === candidate ||
(label.toLowerCase ? label.toLowerCase() : label) === candidate
```

**Comment by webzfactory** [comment]
Any ideas when this will be merged? It looks like a standard use case.

**Comment by bladey** [comment]
Hi @th3fallen,

As pointed out by @Alphonse-Indpro, it appears this PR is no longer required.

However - if you feel this pull request is still relevant for the latest version, let us know and we'll determine if it should be reopened.

**Comment by akre54** [comment]
Thank you for the more thoughtful response here. That pull request doesn't fix the main issue, though, which is that the library is looking for `label` and `value` props on each option and ignoring the `getOptionLabel`/`getOptionValue` functions which are supposed to help in this case.

**Comment by bladey** [comment]
Thanks for letting me know @akre54.

**Comment by ebonow** [comment]
Greetings @th3fallen  ,

Sorry for the extremely late reply to your PR submission. There is quite a backlog of user submitted PR's and the community deserves better than waiting months or years for a collaborator to reply to the work they've done.

I wanted to let you know that the issues that this PR addresses has been resolved:
https://github.com/JedWatson/react-select/pull/3316/files
https://github.com/JedWatson/react-select/pull/4444/files

As such, I will be closing this, thought I feel frustrated for you that this took so long to get resolved and wanted to add that I truly appreciate the time you put into coding a solution. Thank you for being a part of the community and contributing to react-select.

**Pull request closed without merging**
