### PR TITLE
Adds tag creator

### PR DESCRIPTION
**Pull request by flovilmart**
Adds allowCreate=true prop so the field will allow option creation.
By default this option is disable to maintain backward compatibility

### CODE REVIEW

**Comment by dcousens** [comment]
Hi @flovilmart, could you please update this PR without the dist files?
I think this is a cool addition in any case :)

**Comment by flovilmart** [comment]
Ok. I'll do my best :)

**Comment by flovilmart** [comment]
Rebased and removed the commits from the dist and lib

**Comment by bsr203** [comment]
+1

**Comment by beeant** [comment]
+1

**Comment by flovilmart** [comment]
I've updated, and rebased

**Comment by dcousens** [comment]
Thanks @flovilmart this is great.

**Comment by dcousens** [comment]
@flovilmart should a callback be fired to notify of a new tag?

**Comment by flovilmart** [comment]
Not that implémentation, just the on change is fired. That would be a nice feature (but I didn't need it at the time)

**Comment by dcousens** [comment]
@flovilmart thoughts about making a PR for it? :)

**Comment by flovilmart** [comment]
Haha :) you could do it too :p what callback signature would you like? 

Would you want if before or after the change?

Do you want it cancellable?

**Comment by dcousens** [comment]
@flovilmart haha, before the state change is always better, that way the user can throw new props at it if necessary.

> Do you want it cancellable?
That is a good question,  if it was structured properly, we'd handle this like an `onChange` event for a typical field and manage the state in the parent,  but in this case,  the state is being managed internally...

**Comment by flovilmart** [comment]
As for thé signature, I could go with the same as onChange.

Call it onAdd?

**Comment by dcousens** [comment]
@flovilmart sounds good to me

**Comment by flovilmart** [comment]
Just created another PR, maybe we should rename allowCreate to enableAdd, or canAdd or allowAdd, or addEnabled...

**Comment by dcousens** [comment]
`canAdd` works for me.

**Comment by nickbouton** [comment]
+1

**Pull request merged**
