### PR TITLE
Adding createable prop to allow creating of options which were not found

### PR DESCRIPTION
**Pull request by Gregoor**
I required this feature which is afaik also present in Selectize. Let me know if I missed anything or you want to merge it and also need documentatoin.

Also tried to stick to your coding style and lint went through fine.

### CODE REVIEW

**Comment by JedWatson** [comment]
Thanks @Gregoor. I'd like to have a think on the implementation of this, as it would be good to also allow a callback for creating a new option (e.g. if a tag is required in the database to accept an ID - useful for SPAs). Will get back to you soon.

**Comment by AlexMeah** [comment]
:+1: Need this for group selection/creation

**Comment by guzart** [comment]
What are your thoughts so far @JedWatson ? 

Am thinking probably a `createOption` property that returns the option to be added. The function could have the following signature `function(value:string, [callback:func]):object`. 

By default the added option would be `{ value: _optionsFilterString, label: _optionsFilterString}`. If a `createOption` function is specified it could work synchronously by returning the option to be added, or asynchronously if a callback function is specified as the second parameter (arity of 2)

**Comment by barsukov** [comment]
+1

**Comment by dehbmarques** [comment]
+1

**Comment by dcousens** [comment]
Closing, this was added in #151

**Pull request closed without merging**
