### PR TITLE
Fix multi Async option issues

### LINKED ISSUE #1542: Async Multiselect, options dropdown hides every time an option selected
In Async Multiselect (Select.Async), if multi-select is true then options dropdown hides every time an option selected. To see the dropdown I have to search/type. I want to keep dropdown opened instead of hiding it every time after selecting an option like happens in normal Multiselect. 

A gif is attached showing issue

react-select-async-multi

### PR DESCRIPTION
**Pull request by w3-3w**
The first two commits of this PR fixes #1542 and #1561 respectively.
The 3rd ~ 5th commit resolves an inconsistency problem as described in commit message.

As in #1289 , clearing options after selection for multi Async has been a default behavior. I introduced a new prop `clearOptionsOnSelection` , which defaults to true. For those who still need to keep options on selection, set it to `false` and it will behave as it did in v1.0.0-rc.2.

### CODE REVIEW

**Comment by gazpachu** [comment]
I've tested this PR and even if I set `clearOptionsOnSelection={false}`, the options in the select get removed when I start a new search

**Comment by w3-3w** [comment]
@gazpachu By `start a new search` did you mean clicking somewhere outside the component and focusing on it again? Maybe the third commit is questionable, but I think it is better to clear options on blur, because the keyword typed for search will be cleared on blur, or else it creates inconsistency on a second focus.

**Comment by gazpachu** [comment]
@w3-3w the options on a multi select shouldn't be cleared ever. Only when the user clicks on the 'x' icon. ATM, in rc2 and rc3, the options are gone whenever a new search starts. The only become visible again if the search starts with the same letter as the options that were previously selected. For this reason, I had to disable the search funtionality.

I'm not sure if this is exactly the same issue you guys are talking about in this thread.

**Comment by gazpachu** [comment]
No need to click outside the select, the issue happens just by starting a new search after having added a few options on the async multi select.

**Comment by gazpachu** [comment]
@w3-3w Nevermind my previous messages. I've found the issue. It turns out that I was reloading all the options because of the `input` parameter was changing, so I stopped passing the `input` parameter to the API endpoint and now the search works fine. It doesn't remove any option.

**Comment by hsingh23** [comment]
Does this fix the complete issue here: #1514?

**Comment by w3-3w** [comment]
@hsingh23 No. This PR focuses on option display behaviors.

**Comment by amit034** [comment]
any progress?

**Comment by picolll** [comment]
Can someone merge this PR please. I'm waiting for it for a long time now.

**Comment by ndbroadbent** [comment]
This would be awesome, thanks @w3-3w! It would be great if this could be merged (but there's 
a merge conflict now)

**Comment by ndbroadbent** [comment]
@w3-3w i'm using your branch, and the `clearOptionsOnSelection` option doesn't seem to do anything for me. The options are hidden as soon as I select one.

**Comment by ndbroadbent** [comment]
I've tried downgrading to `1.0.0-rc.2`, but then there's a serious bug when using multiple Selects. They all seem to share the same options instead of loading them individually.

**Comment by begincalendar** [comment]
@w3-3w Thank you for creating this PR.

I have some constructive feedback for you:

- I don't think you should conflate two issues with this (or any PR). As far as I can tell you are trying to fix #1542 and #1561 (which are the same issue, so that's fine), but then you also appear to be adding functionality to clear options when the field is blurred. I think the latter part should be stripped out into another PR. What do you think?
- You appear to be doing some refactoring and bug fixing, as well as adding functionality. Related to the previous point, I think refactoring, bug fixing and feature addition should be split into separate PRs. Yes it takes more work on the part of the contributor, but it makes life easier for reviewers of PRs and also for future maintainers/contributors reviewing (master branch) squashed merge commit history. Would you agree?

**Comment by JedWatson** [comment]
Thanks for the PR @w3-3w 

I believe all of the fixes you've included here have been implemented separately (and slightly differently, see the changelog) but this has been a great reference.

For what it's worth in the future, separate PRs for each feature will make it easier to merge 🙂

**Pull request closed without merging**
