### PR TITLE
Enable Flow lint rule implicit-inexact-object and fix issues

### PR DESCRIPTION
**Pull request by nifgraup**
Allows dependant code to enable option exact_by_default.

https://medium.com/flow-type/on-the-roadmap-exact-objects-by-default-16b72933c5cf
https://medium.com/flow-type/how-to-upgrade-to-exact-by-default-object-type-syntax-7aa44b4d08ab

### CODE REVIEW

**Comment by JedWatson** [comment]
Hey @nifgraup sorry but we've ended up with a *lot* of conflicts here, before the PR came up for review.

At first glance, I'd be happy to merge this (and thanks for picking it up!) but would you be up for resolving the conflicts?

Thanks 🙏

**Comment by Methuselah96** [comment]
@nifgraup It's worth noting that we are planning on transitioning away from Flow and to TypeScript in 5.0 (https://github.com/JedWatson/react-select/issues/4142). It's fine if you want to update this PR, just be warned that the changes will likely be overriden by TypeScript in the (relatively) near future.

**Comment by Methuselah96** [comment]
Thanks for the work on this, we've recently converted the code over to TypeScript (https://github.com/JedWatson/react-select/pull/4489) in preparation for v5 so the Flow types will no longer be relevant.

**Comment by nifgraup** [comment]
Sounds like a good conclusion. New Flow libdefs can be derived from the TS code.

**Pull request closed without merging**
