### PR TITLE
Added new prop always-open

### LINKED ISSUE #927: Dev mode react-select
Hi, I noticed a little bit of annoyance when the menu keeps closing after losing focus. Wonder if there is already a way to overcome that while developing. Otherwise, will be `alwaysOpen` option be desirable?

Cheers!

### PR DESCRIPTION
**Pull request by khankuan**
Closes #927

### CODE REVIEW

**Comment by tachang** [comment]
This could be very useful when testing styles for the menu. I keep having to add a breakpoint when the DOM element is removed to style stuff.

Unless there is an easier way.

**Comment by tehkaiyu** [comment]
Could we merge this in? Would love this feature

**Comment by Reggino** [comment]
:+1:

**Comment by willdunning** [comment]
Bump

**Comment by arahansen** [comment]
Would love to use this! 👍

**Comment by tnrich** [comment]
@JedWatson  Please add this feature!

This PR is doing the same thing as https://github.com/JedWatson/react-select/pull/817

**Comment by deanbitan** [comment]
@jedwatson
Hey,
This feature is very important for me, i'll appreciate it if you can pay your attention for it?

**Comment by EnriqueVidal** [comment]
@deanbitan I wrote this as well #1950  not sure if it's still wanted or how to go about merging this in, my PR has no conflicts with master.

**Comment by JedWatson** [comment]
Thanks for the PR @khankuan, I'm going to close it until we have more clarity on #1989

**Pull request closed without merging**
