### PR TITLE
fix for issues #1020 and #2102

### PR DESCRIPTION
**Pull request by sushant-at-nitor**
This fix would address issue #1020 and #2102 without breaking any current implementation.

- change in `componentDidUpdate` we can set the focus to search input if the state is `open` which would not cause problems like  #607 and #1157. The problem which I faced is with tether where the menu was not closing on clicking outside

- change in `handleInputBlur` can give more control to consumer over closing the menu, this helped me close issues #1020 and #2102 when using tether to show menu options where `if` condition fails to identify the click on menu container

### CODE REVIEW

**Comment by yuri-sakharov** [comment]
Hi, 
Will be very good to see fixed and added tests in the PR.
Thanks.

**Comment by sushant-at-nitor** [comment]
@yuri-sakharov fixed async test which was failing due to input focus set through `componentDidUpdate` if the menu is open

**Comment by yuri-sakharov** [comment]
@sushant-at-nitor  thanks and I didn't see new test that cover your added new logic.

**Comment by sushant-at-nitor** [comment]
@yuri-sakharov I have written tests for my code, let me know your comments on the same

**Comment by yuri-sakharov** [comment]
@sushant-at-nitor Very nice. Thank you.

**Comment by sushant-at-nitor** [comment]
@yuri-sakharov can you please help me understand the further steps?

**Comment by yuri-sakharov** [comment]
@sushant-at-nitor need to wait collaborators or owners they will check and will let you know.

**Comment by JedWatson** [comment]
Hey @sushant-at-nitor,

Just wanted to give you an update, I've reviewed this and am not 100% sure because it's an easy API to break... but clearly a valid feature to support. I'm going to release the next version shortly and then review again, thanks for your patience!

**Comment by sushant-at-nitor** [comment]
Thanks @JedWatson

**Comment by BartoszWu** [comment]
Hey @JedWatson any new news about it?

It's almost impossible to use react-select with combination of react-tether in IE10/11 with long list in options. In this case you can only scroll option by mousewheel or just press key down/up to select option that is on end of lists. It's very frustrating :/

If you are not sure about current solution I figure out fix that isn't so dangerous to API break. It's using fix that is working on "normal" situation without react-tether (specially this part: `(this.menu === document.activeElement || this.menu.contains(document.activeElement))` ).
I propose to pass ref for this.menu as argument to menuRenderer. In this case this.menu will point to real HTML DOM element with options and it will use the same part I pasted above with successfull and will focus again input when it's need .
I forked this repo (https://github.com/BartoszWu/react-select/) , add test-case (https://github.com/BartoszWu/react-select/commit/a55165e6f8d9fd5cf0599d4d212041897ef0aeee) and quickly commit fix (you can check fix in this commit: https://github.com/BartoszWu/react-select/commit/608a79813867017c6b21bf1d5afbf64d0657efb6 ). Basically I tested it and it's working fine on IE10/11.
When you are fine with this solution just say and I will create full PR with this fix.

**Comment by sushant-at-nitor** [comment]
Meanwhile I am using a very dirty fix:
`<ReactSelect
  menuClass="Select-menu"
  onBlur={this.onBlur} />`


`onBlur = () => {

    // Fix for IE 11
    if (document.activeElement.classList.contains('Select-menu')) {
      const e = null;
      throw e;
     }
 };`

**Comment by bladey** [comment]
Hi @sushant-at-nitor,

Thanks for this pull request, we appreciate the time you've taken to contribute.

If you feel this pull request is still relevant for the latest version (v3), let us know and we'll determine if it should be reopened and brought up to date to get it merged.

In an effort to sustain the `react-select` project going forward, we're cleaning up and closing old and unmergeable pull requests that relate to old versions of `react-select`.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version (v3) and beyond.

**Pull request closed without merging**
