### PR TITLE
Use react/lib/EventListener instead of document.addEventListener

### PR DESCRIPTION
**Pull request by xcatliu**
`document.addEventListener` doesn't work on IE8.

Use `react/lib/EventListener` instead of `document.addEventListener` will solve this problem.

### CODE REVIEW

**Comment by dcousens** [comment]
@xcatliu please see the CONTRIBUTOR file,  you should only edit files in `src`.  Not `lib`.

**Comment by JedWatson** [comment]
The React team has made it clear that using React internals in other packages is not safe; as tempting as it is to reach in and access these utils, we should find a better way.

**Comment by dcousens** [comment]
Closing,  will open a relevant issue though.  @xcatliu please re-open if you rebase and submit a new/different fix.

**Comment by xcatliu** [comment]
@dcousens @JedWatson 
Ok, I'll find a better way. Thanks

**Pull request closed without merging**
