### PR TITLE
Base aria-live message on tabSelectsValue prop

### PR DESCRIPTION
**Pull request by jkjustjoshing**
If the `tabSelectsValue` prop is set to false, the `aria-live` message is inaccurate. This should fix that.

Addresses #3367

### CODE REVIEW

**Comment by bladey** [comment]
Thanks for the PR @jkjustjoshing!

**Review by Methuselah96 — APPROVED** [review]
Thanks for the PR, this looks good!

**Comment by Methuselah96** [comment]
@jkjustjoshing Can you add a changeset?

**Review by ebonow — APPROVED** [review]

**Review by ebonow — APPROVED** [review]
Looks good!

**Review by JedWatson — APPROVED** [review]

**Pull request merged**
