### PR TITLE
Added an optional instance id property

### PR DESCRIPTION
**Pull request by JevinAnderson**
This will allow synchronization of component id’s on both the server
and the client.

### CODE REVIEW

**Comment by JevinAnderson** [comment]
Should close #1105

**Comment by JedWatson** [comment]
Good solution!

I don't think you need to add the instanceId to the state though. Defaulting to this in the `componentWillMount` method should be sufficient?

```js
this._instancePrefix = 'react-select-' + (this.props.instanceId || ++instanceId) + '-';
```

Did you link to the wrong "should close" issue number btw?

**Comment by JevinAnderson** [comment]
I've updated my solution @JedWatson. Thanks for the suggestion.

**Comment by etburke** [comment]
We're also running into this. Thanks for working out a solution!

**Comment by JevinAnderson** [comment]
@bruderstein @JedWatson 

Any word on this?

**Comment by JedWatson** [comment]
Thanks for that @JevinAnderson, looks good now! Sorry for the delayed merge.

**Comment by mverderese** [comment]
@JedWatson What is your workflow for rebuilding the dist files? I noticed that master is updated with this change, but if I do an `npm install` from master, the dist files are still outdate. I'd like to avoid forking if possible.

Thanks!

**Comment by JedWatson** [comment]
@mverderese I'm about to publish an rc with this fix in it, it should be fine if you update the dependency in your project to that.

**Comment by gabrielflorit** [comment]
I'm still getting the `Warning: React attempted to reuse markup in a container...` warning. I'm on rc2 and I'm passing an `instanceId` to my component (like I believe @JevinAnderson suggested), e.g.

`<Select instanceId='gabrielflorit' ... />`

Am I doing something wrong?

**Pull request merged**
