### PR TITLE
Update Select.js

### PR DESCRIPTION
**Pull request by nhducit**

### CODE REVIEW

**Comment by JedWatson** [comment]
@nhducit I'm not seeing the value of passing `1` to all the `renderLabel` method calls...?

**Comment by nhducit** [comment]
@JedWatson sorry, my bad. I mean "i"

**Comment by nhducit** [comment]
@JedWatson I'm sorry, I got type error. I mean "i"

**Comment by StevenLangbroek** [comment]
@nhducit, could you do 2 things:

- Clarify what benefit we'd get from this. What behavior do you think we can enable by passing the index?
- Fix your typo `1` -> `i`

**Comment by nhducit** [comment]
I fixed my typo
We need `index` variable if we want to display the order of one item. e.g.
```
1. First Item
2. Second Item
```

**Comment by JedWatson** [comment]
This looks good now, I'm happy to merge it. Thanks @nhducit

**Comment by nhducit** [comment]
You're welcome ^^

**Pull request merged**
