### PR TITLE
Updates, fixes, optimization

### PR DESCRIPTION
**Pull request by vadimka123**
1. Fix exists tests for (fixed action meta):
    - should call onChange with `null` on hitting backspace when backspaceRemovesValue is true and isMulti is false
    - should call onChange with an array on hitting backspace when backspaceRemovesValue is true and isMulti is true
2. Simplify small part of code
3. Fixed isValidNewOption when value is null
4. Fixed duplicate declaration in tests
5. Very big performance issue: buildMenuOptions only when menu is opened
    I'm have page with ~1000 selects with a ~1000 options. When render this page it takes ~ 40-50s and while page either hangs terribly or crashed. After this update page render takes 10s and there are no hangs. It's very need update.
6. Fix check for ensure focus. Now code compiled as (isFocused && !isDisabled && prevProps.isDisabled || isFocused && menuIsOpen && !prevProps.menuIsOpen). See https://github.com/prettier/prettier/issues/187

Fixed next issues: 
https://github.com/JedWatson/react-select/issues/3128
https://github.com/JedWatson/react-select/issues/3055
https://github.com/JedWatson/react-select/issues/2970
https://github.com/JedWatson/react-select/issues/2711

### CODE REVIEW

**Comment by kylealwyn** [comment]
Was coming here regarding a similar performance issue where react-select isn't being interacted with yet but is still hogging up the flame graph

**Comment by vadimka123** [comment]
@kylealwyn, please, provide profile

**Comment by mike391** [comment]
@gwyneplaine this is very nice, worth taking a look.  Looking forward to having it merged

**Comment by jacobworrel** [comment]
looking forward to this getting merged. the `buildMenuOptions` is a serious bottleneck when dealing with large lists.

**Comment by vadimka123** [comment]
@JedWatson, any progress on review ?
It's very need

**Comment by piotrwitek** [comment]
@vadimka123 thanks, I'm using your fork and looking great, it's a salvation for my project!

Note for others: It looks like it still requires: `filterOption={createFilter({ ignoreAccents: false })}` to fix perf issues when filtering large options sets.

@JedWatson please could you review this PR? It's solving critical performance issues, very important.

**Comment by abenhamdine** [comment]
@vadimka123 great work, but IMHO your PR mix too much different concerns, and your changes will have more chances to be merged if you break it down in several PR. Eg you could PR only https://github.com/vadimka123/react-select/commit/71b8a37f55795188a93b880aa864bbb39aca0c65, it would be easier to review for the maintainers.

**Comment by vadimka123** [comment]
Changes splited to different PR 
https://github.com/JedWatson/react-select/pull/3566
https://github.com/JedWatson/react-select/pull/3567
https://github.com/JedWatson/react-select/pull/3568
https://github.com/JedWatson/react-select/pull/3569

**Comment by JedWatson** [comment]
That perf fix has been merged with #3569 and will be released in a moment

**Comment by Arthur-Conan-Dog** [comment]
@JedWatson any chance this could be released in July?

**Pull request closed without merging**
