### PR TITLE
Implemented custom option/value label rendering (#203, #45)

### PR DESCRIPTION
**Pull request by brianreavis**
I've been using this for awhile now... just now getting to a PR. This allows for control of how option and value labels are rendered. Related: #203, #45

### CODE REVIEW

**Comment by nickbouton** [comment]
Would be great to see this merged in.

**Comment by janmyler** [comment]
:+1:

**Comment by JedWatson** [comment]
@brianreavis sorry for the delay reviewing this, looks great. Would you mind rebasing so I can merge?

**Comment by sergio-toro** [comment]
:+1:

**Comment by brianreavis** [comment]
@JedWatson Sorry for the delay. Done!

**Comment by JedWatson** [comment]
@brianreavis brilliant, thank you.

**Comment by JedWatson** [comment]
@brianreavis @craigdallimore any ideas on how to set up tests for this?

**Comment by craigdallimore** [comment]
@jed not yet! I'm afraid I'm still grappling with the testing setup - I suspect jsdom is going to be a problem - as far as I can tell it doesn't call handlers for `element.focus()`, which is a fairly [fundamental part](https://github.com/JedWatson/react-select/blob/master/src/Select.js#L322) of how `react-select` works.

Until I can get a test to pass showing that clicking on the component will _present the list of options_ [(this doesn't)](https://github.com/craigdallimore/react-select/blob/test-disabled/test/Select-disabled-test.js#L38-L45), I'm not sure what to recommend for this.

**Comment by dcousens** [comment]
@craigdallimore can we not just test the components state?

**Pull request merged**
