### PR TITLE
Support case-insensitive filtering when matchPos="start"

### PR DESCRIPTION
**Pull request by wesrage**
Fixes Issue #196
Consistent behavior with default (`matchPos="any"`)

### CODE REVIEW

**Comment by dcousens** [comment]
Perhaps this should be an option

**Comment by wesrage** [comment]
I think that makes a lot of sense, with `true` as default.

**Comment by dcousens** [comment]
@wesrage care to add it?

**Comment by wesrage** [comment]
@dcousens Sure.

**Comment by dcousens** [comment]
Thanks @wesrage

**Pull request merged**
