### PR TITLE
Support setting options after value thru props

### PR DESCRIPTION
**Pull request by farism**

### CODE REVIEW

**Comment by JedWatson** [comment]
@farism can you explain this a bit please? looks like some important logic (e.g. `if (newProps.value !== this.state.value)`) has been removed.

**Comment by farism** [comment]
From my understanding, that line of code is purely an optimization technique? The issue is that if options are set after value,  then the component will not be properly updated (and label placeholder does not change). See https://github.com/JedWatson/react-select/issues/74

It's hard to tell without tests, but I don't believe the code is harmful. I don't think there is an issue with calling `getStateFromValue` each time props change. I've been using this fork in a few development projects the past couple weeks, but I cannot make any guarantees.

**Comment by farism** [comment]
Just realized that https://github.com/JedWatson/react-select/pull/53 pretty much addresses the same issue :)

**Comment by dcousens** [comment]
Please rebase.  Happy to merge this or https://github.com/JedWatson/react-select/pull/53

**Comment by Reggino** [comment]
I'm running into the same issue here. The fix looks good, thanks!

**Pull request closed without merging**
