### PR TITLE
Add keepCursorAtEnd prop for single value input

### PR DESCRIPTION
**Pull request by xiaolin**
This will allow single value input to position the cursor at the end of the input string instead of at the beginning. #164 #1874

### CODE REVIEW

**Comment by yuri-sakharov** [comment]
Hi, 

A lot of tests failed. Please fix it.

Thanks.

**Comment by xiaolin** [comment]
Will double check the test, thanks for flagging.

**Comment by xiaolin** [comment]
@yuri-sakharov Fixed the test issues.

**Comment by walifaizy** [comment]
Any Updates on merging this PR @xiaolin @yuri-sakharov

**Comment by yuri-sakharov** [comment]
@walifaizy I did't have permissions for this

**Comment by walifaizy** [comment]
Cool @yuri-sakharov  thanks for the reply, Do you have any idea who is going to merge this PR

**Comment by yuri-sakharov** [comment]
@walifaizy I think owner, collaborators.

**Comment by walifaizy** [comment]
thanks @yuri-sakharov

**Comment by cdm430** [comment]
thanks @yuri-sakharov , would this to be merged in.

**Comment by Berrios** [comment]
@xiaolin @yuri-sakharov @cdm430 @walifaizy @coveralls Any Idea when this PR will be merged in?  or if there is a work around we can do on our end when using the AutoComplete Library component?

**Comment by noisyscanner** [comment]
Any update on this?

**Comment by gorioli** [comment]
Oh, goodness, so many people want it to be merged. I also badly need [this future](https://github.com/JedWatson/react-select/issues/164#issuecomment-366284492).

**Comment by tavareshenrique** [comment]
will not this patch be merged into the project?

**Comment by Veroer** [comment]
+1

**Comment by ebonow** [comment]
Maybe this is minor, but I disagree with the prop name. 

The behavior itself is dependent on the input being `editable` rather than keeping the cursor at the end. I too would like to see this behavior and perhaps even set as default. In the meanwhile, here is an [implementation](https://codesandbox.io/s/react-select-editable-and-selectable-6nfdv) that allows editing and selecting of text.

Note: styles.css is required

**Comment by mindmind** [comment]
What's up?

**Comment by Methuselah96** [comment]
I've started [a fork](https://github.com/react-select-oss/react-select) of react-select. Feel free to resubmit this PR on the fork and we can get it merged and released.

**Comment by ebonow** [comment]
Greetings @xiaolin and thank you for the submission. Also apologies for the long delay in a response.

This PR is a bit out of date with the existing implementation as it was developed against v1. I cannot say whether it would be a good fit when it was first proposed, but much of the library has changed as it's approaching yet another major release and it seems that these changes would no longer be a fit especially since `onBlurResetsInput` was deprecated.

This PR will be closed, though the team and the community appreciate any and all efforts to improve react-select.

**Pull request closed without merging**
