### PR TITLE
[V2]Allow configuring the menuBuffer

### PR DESCRIPTION
**Pull request by wszgxa**
Github issue: https://github.com/JedWatson/react-select/issues/2965

## Overview
Just like the description from the GitHub issue. The components API can't add gap between viewport and menu when you enable `menuShouldScrollIntoView`.So this PR is going to add menuBuffer back.

## Changes
- Add a new props (menuBuffer) in `Select` component, and pass down it to `Menu`
- Use the menuBuffer in `Menu` to add a gap between viewport and menu
- Change the doc 
- `jest --updateSnapshot`

## Question
Do we need to add tests for this one? I guess it's really hard to test it...

I have tested it manually, it works.

### CODE REVIEW

**Comment by zddhub** [comment]
Fortunately, I am also restricted by this issue. Hope this can be release ASAP.

**Comment by wszgxa** [comment]
@jossmac @gwyneplaine Could you help to review this PR?

**Comment by milesjordan** [comment]
I'd love to see this approved too, please!

**Comment by lanmengyujing** [comment]
I would love to be able to use the `menuBuffer` in V2. Hope the PR will approved soon.

**Comment by doudou1212** [comment]
I'm very grateful to your help for reviewing this PR

**Comment by jossmac** [comment]
Hi @wszgxa,

First of all, thanks for putting together this PR, it's very tidy!

@gwyneplaine and I have had a look and we're concerned about the addition of a prop that's so tightly coupled to another i.e. `menuBuffer` only makes sense when `menuShouldScrollIntoView` is `true`.

Please see [my comment](https://github.com/JedWatson/react-select/issues/2965#issuecomment-416107018) on your issue. Happy to discuss further, just being cautious as we have to maintain features indefinitely 🙂

**Comment by jossmac** [comment]
Closing in favour of #2975

The menu placement logic will now respect the margin value on your menu element -- consumer's will be able to use the styles API rather than introducing a new property.

```jsx
<Select
  styles={{
    menu: p => ({ ...p, marginBottom: 76 }}
  }}
/>
```

---

Thanks for [the comment](https://github.com/JedWatson/react-select/issues/2965#issuecomment-416136693) @wszgxa; I hadn't noticed the implicit `menuGutter` expectation.

**Pull request closed without merging**
