### PR TITLE
Add index for multi select values

### PR DESCRIPTION
**Pull request by tonytangau**
This change is for users with drag and drop requirements.

### CODE REVIEW

**Comment by tonytangau** [comment]
Created a drag and drop multi select example based on this PR: [sortable-select](https://github.com/tonytangau/sortable-select)

**Comment by ttttsai** [comment]
This looks great, could we merge this? @JedWatson @gwyneplaine

**Comment by kroeberk** [comment]
Please merge this. This is a great and simple implementation.

**Comment by JedWatson** [comment]
This looks good, thanks @tonytangau (and sorry for the delayed review!)

If you're up for it, adding your example from your [sortable-select](https://github.com/tonytangau/sortable-select/blob/master/src/App.js) repo to the docs would be a great addition to help people understand how to use this feature.

Please open a PR for the "advanced" page if you're up for it!

**Comment by gunn** [comment]
Glad we have this in now.
@JedWatson my PR, which this one comes from, has an example added to the docs too - #3645

**Comment by JedWatson** [comment]
Hey @gunn yeah, I found that after merging this :) working to pull your PR into master now, thanks for that!

**Comment by gunn** [comment]
Awesome. Thank you @JedWatson.

**Comment by loopmode** [comment]
Hey guys. Thanks for adding the index, it really helps! (And not only in drag+drop scenarios :))

Not sure whether this is the right place but it would be great to add this to `@types/react-select` as well! (in `MultiValue.d.ts`)
Is somebody here affiliated with the types package?

**Pull request merged**
