### PR TITLE
ES6 syntax for tests + housekeeping

### PR DESCRIPTION
**Pull request by dmatteo**
While I was working on the tests, I thought it could be helpful to move to a more ES6 syntax, even if not complete.

I basically moved to arrow functions and member functions but I haven't changed `var` to `let/const`.
I've also added a couple of missing traling semicolons

### CODE REVIEW

**Comment by JedWatson** [comment]
@dmatteo can you rebase this for us? and @bruderstein what are your thoughts on this?

Seems safe to adopt ES6 for tests now that we're requiring node 4.

**Comment by bruderstein** [comment]
I'm all for it!

The tests are compiled with babel anyway, because of jsx, so there really are no limits :-)

We could const all the things too 😃

**Comment by JedWatson** [comment]
_facepalm_

haha _of course_ we're using Babel.

Awesome, let's do this :grinning:

**Comment by dmatteo** [comment]
Yeah, I saw Babel, that's why I safely assumed it was ok :)

I'll rebase now

**Comment by dmatteo** [comment]
I'm not sure how could the coverage fell when converting to ES6...

**Comment by JedWatson** [comment]
Great, thanks @dmatteo!

**Comment by dmatteo** [comment]
Cheers!

**Pull request merged**
