### PR TITLE
Add a working example of drag-drop sortable MultiSelect values

### LINKED ISSUE #1606: Repositioning values in multi select
Thoughts on adding support for repositioning values in a multiselect? Preferably via drag/drop.

### PR DESCRIPTION
**Pull request by gunn**
This uses the `react-sortable-hoc` package and is the same approach as #2284. It only makes two small line change tos `react-select` itself.

I think with this we could close #1606, #2284, and #3223.

### CODE REVIEW

**Comment by gunn** [comment]
Can we at least add the [index prop](https://github.com/JedWatson/react-select/pull/3645/commits/47af78d3214d94835a16b484e24c4ee4f4965cae#diff-9545a3fe759773aee9c21703fb5af446)? It's a tiny change, but without it no one can implement functionality like this.

@JedWatson @gwyneplaine

**Comment by bgalek** [comment]
this is awesome, hoping for this change!

**Comment by tonytangau** [comment]
This is a common usage for the `react-select` users. Like @gunn asked, can we at least have the `index` added, so developers can DIY their drag and drop if this is not planned to be supported out of the box. It's a trivial change but provides huge value for the users.

**Comment by tonytangau** [comment]
Created [PR](https://github.com/JedWatson/react-select/pull/3727) and [sample project](https://github.com/tonytangau/sortable-select) for this purpose.

**Comment by kroeberk** [comment]
Yeah please merge this - this is excellent!

**Comment by JedWatson** [comment]
Nice 😀 

I had some issues fixing the conflicts on this branch locally so I've merged it into another one in the main repo for now, will PR that separately to get this live.

Thanks for your work!

**Comment by Shaker-Hamdi** [comment]
Any updates on this, is it now part of the package? and if it is, where can I find the documentation for it?

**Comment by danieljaguiar** [comment]
> Any updates on this, is it now part of the package? and if it is, where can I find the documentation for it?

I found an example here https://react-select.netlify.app/advanced

**Pull request merged**
