### PR TITLE
Add handler for no found event

### PR DESCRIPTION
**Pull request by Lispython**
Added handler for no found event.

It's maybe need to collect not found input and user interests.

### CODE REVIEW

**Comment by dcousens** [comment]
@Lispython please rebase

**Comment by dcousens** [comment]
@Lispython this approach sort-of conflicts with the `noResultsText` prop,  in that it seems odd that you would use both.

@JedWatson thoughts?

**Comment by Lispython** [comment]
noResultsText for different purpose.
I use Select for cities list. Currently our service don't support all cities in out country. Then user try to find city it's view noResultsText message. We log all not found cities requests to Google Analytics via onNoFound callback. And when we collect many of requests we can add new city to out service.

**Comment by dcousens** [comment]
@JedWatson feel free to re-open.  @Lispython this should be handle by your async request then.  There is no reason for the component to call a callback based on external state.

**Comment by JedWatson** [comment]
I agree, best way to handle this is wrap the service call before providing it to `asyncOptions`

**Comment by Lispython** [comment]
I don't use async options in this case. I get list of all cities and give its to options property. 

You say, that this is external state, but noResultsText and filterOptions incapsulated into Select Class.
If I try to handle this case in asyncOptions, I need to duplicate filterOptions and filterOption in asyncOptions function. That sad and not dry...

**Pull request closed without merging**
