### PR TITLE
[v2] Add support for nested option groups

### PR DESCRIPTION
**Pull request by Lolobstant**
It gives the possibility to have nested option group such has:
```
data : [{
  label: String,
  options: [
     { 
       label: String,
       options: [ { label: String, value: Any } ]
     }
  ],
}]
```
can work.

### CODE REVIEW

**Comment by hafezoa** [comment]
What is the timeline on this feature being included in the next release? My team is in dire need of having this and would love to know when we could expect it.

Thank you and great work!

**Comment by Lolobstant** [comment]
Hi @hafezoa, 
i'll commit to resolve conflict this week, afterward i guess it will be up to @JedWatson to merge if it passes his evaluation i guess

**Comment by rojasmi1** [comment]
Any update on this? We're in need of this feature too, would love to know about the timeline.

Thanks :)

**Comment by Lolobstant** [comment]
@rojasmi1 & @hafezoa, conflicts has been resolved, I hope it will be integrated soon ! ^^

**Comment by akre54** [comment]
There are a lot of irrelevant changes as part of this PR. Can you remove those or separate into their own PRs? I'm looking forward to add this to my projects!

**Comment by Lolobstant** [comment]
@akre54  yeah it's due to merging with master, but you can see the modification here > 

https://github.com/JedWatson/react-select/pull/2750/files/c3811ddf3eeb12f58d984cdce04f03403a2cc916

hope it helps

**Comment by hafezoa** [comment]
This has been sitting around for a month! 😢

**Comment by sag1v** [comment]
Would be cool if we can select an entire group

**Comment by Lolobstant** [comment]
@sag1v I'll try to look into it this week, at least to have an idea on how difficult it would be to implement. although I'm not sure it is relevant since it doesn't look like this feature will be merged anytime soon.

**Comment by spacecowboyian** [comment]
> @sag1v I'll try to look into it this week, at least to have an idea on how difficult it would be to implement. although I'm not sure it is relevant since it doesn't look like this feature will be merged anytime soon.

Any movement?

**Comment by liviudobrea** [comment]
Come on boys

**Comment by vrinceanuv** [comment]
Any movement on this one?

**Comment by stdmn** [comment]
Would be awesome to have this implemented.

**Comment by lukaszkikowski** [comment]
Are there any plans to accept this?

**Comment by zgallagher08** [comment]
Looking forward to this getting merged

**Comment by vrinceanuv** [comment]
Was this merged or just closed without any comments?

**Comment by rash2x** [comment]
Anybody?

**Comment by gothbarbie** [comment]
What happened to this feature @gwyneplaine?

**Comment by vikasraok** [comment]
Need this.

**Comment by patrickDouglas** [comment]
Would love to have this built-in.

**Comment by jjacobWT** [comment]
Any plans for this to make its way into v3?

**Comment by JaredDahlke** [comment]
need this

**Comment by neoncube2** [comment]
I'm thinking that the author felt that there were too many changes in this pull request and therefore closed it. Is that correct, @gwyneplaine?

**Comment by ebonow** [comment]
Greetings, 

I am not sure under what context this issue was closed. 

At the moment, though, I can say that the priority is on fixing priority bugs and resolving existing PRs quickly so we can focus on version 4 which would involve a move from Flow to TypeScript. That said, I'd be very interested in having a discussion about impact and expectations.

It's often the case that some PR's can open the door to many more feature requests and maintenance, so I think it'd be fair to discuss the merits/impact/expectations before taking on something like this especially when the collaboration team is spread so thin.

**Comment by neoncube2** [comment]
Thanks, @ebonow!

Could we perhaps reopen https://github.com/JedWatson/react-select/issues/3173, so we can continue discussion there?

**Comment by ebonow** [comment]
@neoncube2 

In the interest of separating feature requests, questions, support, and other ideas from actual bugs and issues, I would prefer to leave the issue closed and instead leverage the Discussion section of this repo.

In the interest of doing so, I have created a Discussion for this topic here https://github.com/JedWatson/react-select/discussions/4315

If anyone has any other feedback or support for this, please feel free to join in there.

**Pull request closed without merging**
