### PR TITLE
Fix scrolling issues

### PR DESCRIPTION
**Pull request by vadimka123**
https://github.com/JedWatson/react-select/issues/3232
https://github.com/JedWatson/react-select/issues/2862

### CODE REVIEW

**Comment by releaf** [comment]
@JedWatson - It would be awesome to have this fix merged in.

**Comment by CuongLai** [comment]
@JedWatson I agree with @releaf - would really help me out to have this fix merged in.

**Comment by vadimka123** [comment]
@JedWatson, any update?

**Comment by shivam-kantival-mt** [comment]
@JedWatson, any updates on this?

**Comment by prajjawalagarwal** [comment]
@JedWatson @vadimka123 we are also facing this scrolling issue. Any updates on when can this be merged into master?

**Comment by jasveer1997** [comment]
@vadimka123 I think the proposed solution does not work correctly(needs a minor change) for the following case: 
For me, it was fetching data correctly only for the first time. Then, I had to drag scrollbar up, leave it, and scroll down again.
Therefore, I have to to add `this.handleEventDelta(event, 1)` in the `onMouseDown` fn, to reset `isBottom` prop in `handleEventDelta`back to false. (this resetting happens for touchbar automatically).

**Comment by aron-hivebrite** [comment]
Hello @vadimka123,
Firstly, thanks for your work.
I have tested your solution but I still see a bug when I use the react-select on a **mobile** and **using a modal**, I cannot scroll the options.
I have modified an existing code in codesandboxer to show you the bug:
https://codesandbox.io/s/react-codesandboxer-example-forked-vmhpl?file=/index.js
Could you check it please?
Thanks in advance.

**Comment by aron-hivebrite** [comment]
Hello @vadimka123,
Thanks for you update. Did you verify the tests failed on CircleCI please?
I am very interested to test your last update.
Thanks in advance.

**Comment by vadimka123** [comment]
Hi, @aron-hivebrite 
I checked issue with react-select 3.1.0
It's have same issue and looks like not related to my changes 
You also can check here: https://codesandbox.io/s/react-codesandboxer-example-forked-12n5d
Most likely existing touch events damage this

**Comment by Methuselah96** [comment]
I've started [a fork](https://github.com/react-select-oss/react-select) of react-select. Feel free to resubmit this PR on the fork and we can get it merged and released.

**Pull request closed without merging**
