### PR TITLE
Allow input to be updated with onInputChange

### PR DESCRIPTION
**Pull request by brettdewoody**
Allows the input to be modified by returning a value from `onInputChange`. 

Refs #893.

### CODE REVIEW

**Comment by bruderstein** [comment]
@brettdewoody see https://github.com/bruderstein/react-select/commit/f964825624df9447cc0d05de8506cb516fe2b49b for my suggestion :)

**Comment by brettdewoody** [comment]
As expected, much better. Should I close this PR in favor of [bruderstein@f964825](https://github.com/bruderstein/react-select/commit/f964825624df9447cc0d05de8506cb516fe2b49b)?

**Comment by bruderstein** [comment]
No, just grab my commit if you like it, and add it to your branch -  it's
still your PR. Glad I could help out.

**Comment by JedWatson** [comment]
Thanks @brettdewoody! Looks great.

**Pull request merged**
