### PR TITLE
Fix error with "Invalid attempt to destructure non-iterable instance"

### LINKED ISSUE #2755: [V2] Invalid attempt to destructure non-iterable instance
It only happens in Android 4.3

### Traceback
TypeError: Invalid attempt to destructure non-iterable instance
- File "webpack:///./node_modules/react-select/dist/react-select.es.js" line 145 col 1 in E
throw new TypeError("Invalid attempt to destructure non-iterable instance");
- File "webpack:///./node_modules/react-select/dist/react-select.es.js" line 3445 col 1 in HTMLDocument.onTouchStart
var _ref2$touches = slicedToArray(_ref2.touches, 1),

### PR DESCRIPTION
**Pull request by xakep139**
Fix #2755

### CODE REVIEW

**Comment by xakep139** [comment]
@ReiiYuki, I've implemented your suggestions

**Comment by ReiiYuki** [comment]
I'm wondering why does the test fail???

**Comment by xakep139** [comment]
I suppose failed tests were fixed in #3253

**Comment by xakep139** [comment]
@ReiiYuki, I've created #3302 from scratch as replacement of this PR

**Comment by ReiiYuki** [comment]
@xakep139 Thanks !

**Pull request closed without merging**
