### PR TITLE
Fix onCreateOption is not always called for Creatable

### PR DESCRIPTION
**Pull request by nikitaindik**
**Issue**: https://github.com/JedWatson/react-select/issues/3988

The issue is caused by "newOption" being recreated as a new object on every render.

### CODE REVIEW

**Comment by johannesleander** [comment]
Any update on plans to release this fix?

**Comment by bcalvignac** [comment]
Yes, this was causing me problems too

**Comment by sirjuan** [comment]
This issue (comparing with reference) sometimes causes `onCreateOption` to not be called. Instead `onChange` with `select-option` action is called with new option object.

Merging and releasing this PR would fix it.

**Comment by laznic** [comment]
Could this fix get merged please? Thanks in advance!

**Comment by makker** [comment]
Would be greatly appreciated if this fix could be released! 🙏

**Comment by mika-kaki** [comment]
Looking forward for this fix. Thanks for your great work!

**Comment by bladey** [comment]
@JedWatson this looks good to me - pending your review.

**Comment by nikitaindik** [comment]
@bladey @JedWatson Hi guys! Do you think we can merge this? :)

**Comment by Methuselah96** [comment]
I've started [a fork](https://github.com/react-select-oss/react-select) of react-select. Feel free to resubmit this PR on the fork and we can get it merged and released.

**Review by Methuselah96 — DISMISSED** [review]
@nikitaindik Thanks for the PR!

1. Can you add a test?
2. My preference would actually be to change the behavior in `Select.js` to only memoize the options when they are strictly equal by changing `isEqual(newProps.options, lastProps.options)` to `newProps.options === lastProps.options` [here](https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/Select.js#L381) (might as well change the other ones from `isEqual` to `===` as well). This allows people to use strict equality in their own `onChange` methods and not have to worry about the implementation detail that the memoization depends on an internal `isEqual` method. This memoization was introduced in https://github.com/JedWatson/react-select/pull/3868 and I don't believe the memoization was essential to the fix in that PR.

**Comment by nikitaindik** [comment]
Hi @Methuselah96! I'll have some spare time during the weekend. I'll try to add a test see if I can resolve this isEqual thing.

**Comment by Methuselah96** [comment]
@nikitaindik Let me know if you don't have time to make the changes. I can do it myself if you don't have the time.

**Comment by nikitaindik** [comment]
Yep, sure. I'm still a little busy. Sorry. Please feel free to improve this
PR.

**Review by JedWatson — APPROVED** [review]

**Pull request merged**
