### PR TITLE
Re-added the focus() method on Select.Async

### PR DESCRIPTION
**Pull request by mcls**
For more info see #1330

### CODE REVIEW

**Comment by mcls** [comment]
Could any of the maintainers take a look at this? It would be really handy to have this again.
If there's a better way, or there are other concerns, please let me know.

Thanks

**Comment by blairbodnar** [comment]
Also waiting on this to be implemented again as well. Thanks!

**Comment by JedWatson** [comment]
Thanks @mcls!

Looks good, and sorry for the delay.

**Comment by mcls** [comment]
No problem, thanks for merging

**Pull request merged**
