### PR TITLE
Don't open drop down menu when clear values

### PR DESCRIPTION
**Pull request by Chopinsky**
This PR is to address issue #1252, where when "clear" button is clicked upon, the drop down menu will prompt to open. This issue is caused by involuntarily firing the focus event after clearing values, where we will prompt the menu regardless of the context.

To address this issue, we will set a flag in the `clearValue` function, and then reset the flag after the focus handler finishes.

### CODE REVIEW

**Comment by garrettdehnketurpin** [comment]
Just curious, on when this branch will be merged?

Regards,
Garrett

**Comment by JedWatson** [comment]
Opening when the clear button is clicked was originally intended behaviour, but having tested the two this does make more sense. Seems like if the user intention is to clear the field, it doesn't necessarily also convey an intention to open the menu... right?

This also makes the "clear" behaviour consistent with the behaviour of the "remove" icon on values in a multi-select, so I'm happy to merge it.

Would you mind resolving the conflict @Chopinsky? I've taken a look and am not 100% confident how to preserve your fix without digging deeper into it.

**Comment by JedWatson** [comment]
Nevermind, I'm about to release a version and want to include this so I've dug in deeper and resolved the conflicts. Thanks for the PR @Chopinsky!

**Comment by samuelcolvin** [comment]
Any chance of getting a release with this included?

**Pull request merged**
