### PR TITLE
Adding index sortable example

### PR DESCRIPTION
**Pull request by aschmoe**
RE: #91 

Adds react-sortable-hoc example, adds index prop to ValueComponent

Work largely done by @pwhipp

### CODE REVIEW

**Comment by JedWatson** [comment]
@aschmoe this looks great! I'm about to publish a new patch version with other small fixes, and don't have time to review this fully before then but will come back to it asap.

Would you mind amending the PR to not include the changes to the build files please? `dist` and `lib` get updated when I publish new versions, including them in PRs can be problematic. We just need the changes to the `src` and style folders.

Thanks!

**Comment by aschmoe** [comment]
@JedWatson build files have been removed

**Comment by wimoMisterX** [comment]
@JedWatson when could I expect a release with this PR being merged?

**Comment by liegeandlief** [comment]
@aschmoe - Really like this! One thing I noticed is that when clicking on an option to drag it, it causes the select input to open. Is it possible/desirable to prevent this?

**Comment by elyobo** [comment]
A useful example to have, can we get this conflict resolved so that it can be merged?

**Comment by JedWatson** [comment]
Thanks everyone who had a hand in this - with #3792 it's finally live

**Pull request closed without merging**
