### PR TITLE
Reload defaultOptions when cacheOptions changes in Async

### PR DESCRIPTION
**Pull request by wouterhund**
Previously the default options did not reload when the cache changes, leading to incorrect results.

### CODE REVIEW

**Comment by Guichaguri** [comment]
I'm also experiencing this issue in three async selects:
* Country
* State: depends on the country
* City: depends on the state and country

It's working as expected, but only when using the search. The defaultOptions are not being reloaded properly.

**Comment by bladey** [comment]
Hi @wouterhund,

Thanks for this pull request.

In an effort to sustain the `react-select` project going forward, we're cleaning up and closing old and unmergeable pull requests that relate to old versions of `react-select`.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

Additionally - if you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However - if you feel this pull request is still relevant for the latest version, let us know and we'll determine if it should be reopened and brought up to date to get it merged.

**Comment by oowowaee** [comment]
@bladey Seeing this in the latest version as well.  My use case was the options of the select are determined based on the value of another select, which I am passing in as the cache key.  I was expecting that since the cache key had changed, it would refetch the defaultOptions, but that is not the case.  As @Guichaguri mentioned above, it works correctly when typing, as the cache has been cleared, but it looks like the request for loadOptions('') is not reissued when the cache key changes.  Will have to investigate managing the defaultOptions manually.

**Comment by ebonow** [comment]
Greetings @oowowaee ,

Since AsyncSelect will do a fetch on each key down, defaultOptions is meant to provide a first time experience when the input is first focused. After that, `loadOptions` can be used for input (including inputValue === '')

`defaultOptions` can be several things...

First and foremost, a boolean will cause the AsyncSelect to call loadOptions with an empty string for inputValue if truthy. 

However, defaultOptions can also be a list of options. Therefore you could create a function which would return a list of options based on some criteria. Since this is used by the initial state, you may want to use this same type of logic in your loadOptions call when the inputValue === ''.

it's worth noting that "default" in most contexts will only refer to the initial value of something on mount similar to setting default state value in a class component in the constructor.

**Comment by oowowaee** [comment]
@ebonow Thanks!  I found https://github.com/JedWatson/react-select/issues/1879 after commenting, and look forward to when that functionality is added.  For the moment the key workaround solves the issue!

**Pull request closed without merging**
