### PR TITLE
fix bug, if wrote "hasOwnProperty"

### PR DESCRIPTION
**Pull request by SuhushinAS**

### CODE REVIEW

**Comment by agirton** [comment]
Hi @SuhushinAS thank you for the PR. What’s the use case?

**Comment by SuhushinAS** [comment]
Hello!
Sorry for my English.
See the attached picture to get bug:
screenshot_1

**Comment by JedWatson** [comment]
Nice, good fix @SuhushinAS

**Comment by JedWatson** [comment]
@jochenberger what's going on here:

The cache uses the `Object` prototype, the bug here is that adding a property called `hasOwnProperty` to the cache object overrides it. So calling the method on `Object.prototype` is a neat workaround.

**Pull request merged**
