### PR TITLE
Draggable Value for Multiselect

### PR DESCRIPTION
**Pull request by songyanho**
Integrated the [react-dnd](https://github.com/react-dnd/react-dnd) with react-select.

With `draggable` and `multi` enabled, draggable feature is enabled.

DragDropContext is required.

With either of the methods should be implemented to enable the drag-and-drop feature
1. Put `DragDropContextProvider` as root if more than one draggable is used.
```
import HTML5Backend from 'react-dnd-html5-backend';
import { DragDropContextProvider } from 'react-dnd';

<DragDropContextProvider backend={HTML5Backend}>
# Content here
</DragDropContextProvider>
```

2. Use DragDropContext manually
```
import HTML5Backend from 'react-dnd-html5-backend';
import { DragDropContext } from 'react-dnd';

@DragDropContext(HTML5Backend)
export default class YourApp {
  /* ... */
}
```

### CODE REVIEW

**Comment by songyanho** [comment]
1. This commit also includes update of PropTypes from React.PropTypes
2. I have not prepared the documentation yet, but soon after this is approved?

**Comment by agirton** [comment]
Hi @songyanho Thank you for starting this! I'm a bit apprehensive on adding draggable to the project. Let's see if anyone else in the community would like this also.

Do you mind rebasing as the PropType changes were merged into master recently?

**Comment by songyanho** [comment]
Thank you for reviewing my PR. I have merged with the latest master.

**Comment by songyanho** [comment]
Any updates?

**Comment by agirton** [comment]
Hi @songyanho, this won't make the 1.0 release. Also it seems this could be accomplished in user land if we exposed more props for the Value Component.

**Comment by songyanho** [comment]
@agirton I can work on the changes to submit another PR

**Comment by arift** [comment]
This would be a very welcome addition. Not sure why it didn't make it to 1.0.

**Comment by Hongbo-Miao** [comment]
Yeah, it is a very useful feature.

**Pull request closed without merging**
