### PR TITLE
Allow to set placement of the new option

### PR DESCRIPTION
**Pull request by leesiongchan**
This might be useful when someone wish to customize the position of the new option.

### CODE REVIEW

**Comment by JedWatson** [comment]
Looks good, can I suggest naming the prop `newOptionPosition` though? `placement` is a bit ambiguous.

**Comment by leesiongchan** [comment]
@JedWatson Alright, I have updated the commit.

**Comment by leesiongchan** [comment]
ping @JedWatson

**Comment by leesiongchan** [comment]
ping @JedWatson

**Comment by leesiongchan** [comment]
ping @JedWatson

**Comment by gwyneplaine** [comment]
thanks for this @leesiongchan, closing this in favor of https://github.com/JedWatson/react-select/pull/1436 which will be merged in post release 1.0

**Pull request closed without merging**
