### PR TITLE
Add resultLimit prop limiting the amount of rendered options

### PR DESCRIPTION
**Pull request by h3rmanj**
Add a `resultLimit` prop that prevents rendering too many results. Useful if the number of options are in the thousands.

Indirectly addresses #4504  
Addresses #4516

### CODE REVIEW

**Comment by Methuselah96** [comment]
Could you filter the options before passing them into the Select component?

**Comment by h3rmanj** [comment]
> 
> 
> Could you filter the options before passing them into the Select component?

I could, yeah. But it's incredibly frustrating that I'd have to hoist and manage input state and search logic, which Select already has, just because i want to limit the amount of options that are rendered. This feature would be really helpful to have available, when dealing with thousands of options, which is often the case.

**Comment by ThomDevine** [comment]
I cannot filter options before passing them into react-select, because some of our lists have big numbers (1200+ is slow in IE11) and I want to make use of the typeahead filter.

I tried using a custom MenuList component to render a single "Too many results - keep typing" option until the list is under the limit.  But in MenuItem, props.children already exists and altering the props.options list does nothing.

If there is a higher-level component that has "the list of filtered options" and does NOT already have "the rendered list of options as props.children", that will work.  I have not found this component in the docs though.  If someone can tell me here if that component exists and what it is, it will solve the "max options" issue without an API change.

If it exists, it's probably worth adding to the Examples page.

**Review by brotherbarz — APPROVED** [review]

**Comment by h3rmanj** [comment]
Closing because of the major rewrite in progress.

**Pull request closed without merging**
