### PR TITLE
enable consumers to require less files programmatically

### PR DESCRIPTION
**Pull request by alanclarke**
moved from https://github.com/JedWatson/react-select/pull/198 to custom branch

### CODE REVIEW

**Comment by dcousens** [comment]
Thanks @alanclarke

**Comment by dcousens** [comment]
@alanclarke can you please add an example here as to how this could work for users?

**Comment by dcousens** [comment]
@JedWatson please double verify,  can still revert if necessary.

**Comment by alanclarke** [comment]
heya @JedWatson, thank you for merging! :+1: 

[Here](https://github.com/alanclarke/lessify-react-select-example) is a working example of how this can be used.

**Pull request merged**
