### PR TITLE
Reset options onBlur for Async Select when onBlurResetsInput is true

### PR DESCRIPTION
**Pull request by scags9876**
Addresses Issue #751

### CODE REVIEW

**Comment by scags9876** [comment]
Woohoo!  coverage increased!

**Comment by dan-brewster** [comment]
@scags9876 Hello, I wanted to check in on the status of this PR. The underlying issue is currently a blocker for our implementation of react-select and I wanted to see if there's anything that is blocking it from being merged (aside from the conflict). I'd be happy to fix the conflicts if that would help get it in. Thanks!

**Comment by scags9876** [comment]
@dan-brewster afaik, this is just waiting on a review and merge from @JedWatson or another maintainer.

I didn't realize some conflicts have crept in.  I'll fix them and repush

**Comment by gauthamchandra** [comment]
Any movement on this? I could totally use this fix at the moment. I can fix the merge conflicts and reissue a PR if needed.

**Comment by gwyneplaine** [comment]
@scags9876  thanks for this,  #751 has been solved differently in https://github.com/JedWatson/react-select/pull/1306 which has been pulled into master.

**Pull request closed without merging**
