### PR TITLE
[v2] Pressing <Enter> in IME mode should not select a option

### PR DESCRIPTION
**Pull request by shamabe**
In composing mode, enter key is for selecting a suggest of conversion.
So that, the behavior of enter key is collision in "react-select" with IME.

Like this...
react-select-before

It is necessary to check whether it is in composing-mode or not.
Following is the preferred behavior.

react-select-after

### CODE REVIEW

**Comment by JedWatson** [comment]
This looks great @shamabe, thanks!

**Comment by maplesyrupsucker** [comment]
@gitcash send 0.005 BCH to @shamabe

**Comment by maplesyrupsucker** [comment]
@gitcash send 0.0025 to @shamabe for being amazing at vim

**Comment by maplesyrupsucker** [comment]
@gitcash send 0.005 BCH to @shamabe for being amazing at vim

**Comment by maplesyrupsucker** [comment]
@gitcash send 0.0025 BCH to @shamabe

**Comment by GitCash** [comment]
Hey **shamabe**, user **maplesyrupsucker** tipped you **2500 bits** in Bitcoin Cash ( ~ **$1.8125** ).

*[Click here to claim it!](https://gitcash.io/claim/shamabe)*

You can also add the "thumbs down" reaction to **maplesyrupsucker**'s comment above to prevent future tips.

**Pull request merged**
