### PR TITLE
Async options with Promises - Promise object bug

### PR DESCRIPTION
**Pull request by VladimirPal**
https://github.com/JedWatson/react-select/issues/940

### CODE REVIEW

**Comment by VladimirPal** [comment]
I've broken tests, trying to figure out...

**Comment by JedWatson** [comment]
@VladimirPal wow, thanks for not just fixing this but adding a compete example! great work 👍

**Comment by f2net** [comment]
In the /lib folder I still see the old Select.js without this fix. Why?

Thank you,
Matteo Frana

**Comment by VladimirPal** [comment]
@f2net It's because lib folder builds automatically after releasing new version, looks like you have to build it manually:
`cd node_modules/react-select`
`npm install && npm build`

**Comment by VladimirPal** [comment]
@JedWatson Maybe you can build current state of project or release new version? I think this bug is pretty important

**Comment by f2net** [comment]
@JedWatson @VladimirPal I agree, I think the current state should be built, otherwise who installs the package via npm without building gets the [Promise object] bug. 
Thank you for this great component.

**Comment by eliseumds** [comment]
May we have a release?

**Comment by f2net** [comment]
Could you update the /lib version too, since the file in the /lib folder is still bugged?
Every time I distribute an app with react-select async I have to manually change line 390 of Select.js in /lib to:
```javascript
if (nextState != null && typeof nextState !== 'object') {
```
Thank you,
Matteo

**Comment by jeffreybrowning** [comment]
I would love a release.

**Comment by khankuan** [comment]
@JedWatson any chance of a release soon? :)

**Comment by TrevorBurnham** [comment]
FYI I've published a release of the [react-select-plus](https://github.com/HubSpot/react-select-plus) with this patch, `1.0.0-beta13.patch1`.

**Pull request merged**
