### PR TITLE
Fix for create with custom value / label fields

### LINKED ISSUE #2953: [V2] Creatable throws with custom value / label fields
## Description: 
Go to https://codesandbox.io/s/qj18wmroj and start typing in the select box. Throws `TypeError: Cannot read property 'toLowerCase' of undefined`.

## Cause: 
Creatable.js's [https://github.com/JedWatson/react-select/blob/v2.0.0-beta.7/src/Creatable.js#L41-L42](`compareOption`) function incorrectly assumes the `options` object has `label` and `value` properties.

## Possible Fix
`compareOption` should use `getOptionLabel` / `getOptionValue` before referencing the properties.

### PR DESCRIPTION
**Pull request by akre54**
Fixes #2953

### CODE REVIEW

**Comment by akre54** [comment]
Ping @JedWatson @gwyneplaine

**Comment by IanVS** [comment]
I'd love to see this get merged to fix a pretty serious bug.  Any chance it can get some eyes on it?  There are several other PRs open right now also attempting to solve the same thing: 

- https://github.com/JedWatson/react-select/pull/3004
- https://github.com/JedWatson/react-select/pull/2990

**Comment by bladey** [comment]
Hi @akre54,

Thanks for this pull request.

In an effort to sustain the `react-select` project going forward, we're cleaning up and closing old and unmergeable pull requests that relate to old versions of `react-select`.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

Additionally - if you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However - if you feel this pull request is still relevant for the latest version, let us know and we'll determine if it should be reopened.

**Comment by akre54** [comment]
@bladey This is super annoying. Closing with a form message after nearly 2 years of ignoring these pull requests is a slap in the face to me and others who took the time to report these issues, track down the problem and propose a fix. Please at the very least look at the solution and consider the failing test case.

**Comment by JedWatson** [comment]
Hi @akre54 sorry you've had that experience - no slap in the face intended, so thanks for sharing your perspective on how this comes across ❤️ 

To try and explain better, right now we have an overwhelming amount of issues and PRs to triage and it's extremely difficult and time consuming to go through each one to _even know if they're still relevant_. We **do** want to respond to and resolve the ones that are current, but will be able to do that much better with the community's help. So @bladey is closing ones that _look_ old enough that they're probably outdated and so far we've had mostly good experience getting feedback from people when some should be reopened.

So one of the metrics we've looked at is "does this look like it stopped being an issue; if so, close it; if not, there'll be recent activity or people will let us know"

It's a blunt way of prioritising contributions for sure, and I'm sorry about that. Maybe we can improve our wording on the standard text @bladey is using to clarify our intention here.

With regards to this particular issue, I've taken a look and the props `formatCreateLabel`, `isValidNewOption` and `getNewOptionData` props were introduced to `Creatable` to fix this and other related issues that were present in the version you opened this PR against.

It's a slightly different solution to the one you proposed here, but fixes this and other limitations, and is covered comprehensively by tests.

My apologies for not having had the chance to respond properly to the PR when you originally opened it.

**Comment by akre54** [comment]
Thanks for the thoughtful response, @JedWatson. As an ex-maintainer of a big project I can certainly sympathize with the amount of work this takes.

I updated my outstanding pull requests and I'll check out the latest changes to Creatable. It'd be nice to be able to deprecate my fork.

**Pull request closed without merging**
