### PR TITLE
optionRenderer inputValue

### PR DESCRIPTION
**Pull request by ijohnson888**
The optionRenderer will now have access to the inputValue from the
state. #783

### CODE REVIEW

**Comment by jnleonard3** [comment]
:+1:

**Comment by thomasbottonari** [comment]
:+1:

**Comment by mrqcmc** [comment]
👍

**Comment by Tommy10802** [comment]
:+1:

**Comment by JedWatson** [comment]
Thanks for the PR @ijohnson888 

This is a good idea but the rendering code has been completely rearranged so unfortunately I'm going to have to close this. Will be looking to simplify how custom rendering can be implemented with access to more state very soon though, so this feature should be supported when that lands.

**Pull request closed without merging**
