### PR TITLE
add duplicate support for multi select

### PR DESCRIPTION
**Pull request by kimyu92**

### CODE REVIEW

**Comment by kimyu92** [comment]
@gwyneplaine It is highly appreciated if you can review this PR in order to support duplicate feature for multi select against v1.x branch. Please feel free to reach out to me if you have any question. Thank you.

**Comment by switz** [comment]
Wow, this is what I just so happen to be looking for, though mostly in regards to a `Creatable`. I presume they're quite intertwined. I was hoping I could just pass `isValidNewOption={() => true}` but it seems to override on duplicate values unfortunately. Perhaps this would enable that to work.

Happy to help push this through in any way if I can offer support/code.

**Comment by kimyu92** [comment]
> Wow, this is what I just so happen to be looking for, though mostly in regards to a `Creatable`. I presume they're quite intertwined. I was hoping I could just pass `isValidNewOption={() => true}` but it seems to override on duplicate values unfortunately. Perhaps this PR would enable that to work.
> 
> Happy to help push this through in any way if I can offer support/code.

🤞

@JedWatson btw, any idea on how to move forward with this PR?

**Comment by Cadrach** [comment]
Any updates on this?

**Comment by flexdinesh** [comment]
Hey @kimyu92 [v1 of react-select is no longer maintained](https://github.com/JedWatson/react-select/pull/3786). 

We recommend maintaining your own v1 fork if you want to address `v1` issues. We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest versions.

We highly recommend [upgrading from v1 to v2](https://react-select.com/upgrade-guide).
I'm closing this issue now. Feel free add your thoughts in #3981 and reference this issue if you must.

**Pull request closed without merging**
