### PR TITLE
Update changelog

### PR DESCRIPTION
**Pull request by Noviny**
Update of changelog files for rc.3

### CODE REVIEW

**Comment by jochenberger** [comment]
#1226 should be mentioned, since it is a breaking change (not the kind to do from one rc to another, if you ask me).

**Comment by Noviny** [comment]
@jochenberger I wasn't sure how to summarise that one properly, so I'm waiting for @JedWatson to add that one in.

**Comment by JedWatson** [comment]
I'll add that - good point @jochenberger, we'll try not to do that again, tbh I was more focused on the issues it fixed than the fact that it was an API change, sorry!

**Comment by JedWatson** [comment]
Thanks for this @Noviny - much appreciated!

**Pull request merged**
