### PR TITLE
Fix async with multiselect

### LINKED ISSUE #1542: Async Multiselect, options dropdown hides every time an option selected
In Async Multiselect (Select.Async), if multi-select is true then options dropdown hides every time an option selected. To see the dropdown I have to search/type. I want to keep dropdown opened instead of hiding it every time after selecting an option like happens in normal Multiselect. 

A gif is attached showing issue

react-select-async-multi

### PR DESCRIPTION
**Pull request by dekelb**
This PR fixes #1542 and #1561
Original PR that caused this issue: #1508

### CODE REVIEW

**Comment by dekelb** [comment]
@JedWatson Did you manage to check this pr? Will appreciate if you can merge and release a new version as this fix a really problematic behavior with the async multiselect.

Thanks!

**Comment by dekelb** [comment]
@JedWatson, @agirton now that this package get a bit more attention, can you please check this pr? Thanks!

**Comment by agirton** [comment]
Hi @dekelb thank you for your contribution. It seems like this would call the API, what's the primary goal for adding the additional method calls?

**Comment by dekelb** [comment]
@agirton the main issue was introduced in https://github.com/JedWatson/react-select/pull/1508/files, in my code I was trying to revert that issue and fix the original problem there.

The original problem was that when the value was changed, the internal list was not cleared, and there was nothing to show after choosing the first value. Clearing the internal state with `this._onInputChange('');` fixed that.

**Comment by ericnewcomer** [comment]
This is the same issue described in #1753 as well, so I'm behind getting a solution merged for this. Haven't looked through this PR yet, but reissuing the empty query is along the lines of what I was proposing.

**Comment by agirton** [comment]
Hi @dekelb haven't pulled this down locally, but couldn't you solve this by just removing the clearOptions method call without having to add two additional inputChange calls?

**Comment by dekelb** [comment]
@agirton I tried using `this.clearOptions` but it didn't work (maybe it's related to some other issues, it looks like it doesn't trigger the relevant callbacks, setting focus for example, getting the relevant list of items, etc). I know this package is getting better attention these days, maybe now with some other fixes the `this.clearOptions` will work, I admit that I didn't try it in v1.0.0-rc.5

**Comment by gwyneplaine** [comment]
thanks for this @dekelb, this has been fixed in a separate body of work by @JedWatson, 
outlined here https://github.com/JedWatson/react-select/issues/1542#issuecomment-328919546
you can find the commit here https://github.com/JedWatson/react-select/commit/c7fe6f44763d680313ef7620e3c5373c87b8e319

**Pull request closed without merging**
