### PR TITLE
refactor to use class syntax

### PR DESCRIPTION
**Pull request by pr1ntr**
I converted all the createClass stuff to use class syntax.

### CODE REVIEW

**Comment by pr1ntr** [comment]
I dunno... they fail on master anyway.

**Comment by uxtx** [comment]
i see the same error - it's due to a breaking change in react 15.3.0, i believe.

**Comment by uxtx** [comment]
i've got an issue open here: https://github.com/facebook/react/issues/7418

**Comment by pr1ntr** [comment]
fixed this PR. reset all the built files

**Comment by bvaughn** [comment]
Curious...what's the motivation behind this PR?

I'm also a fan of the class syntax for stateful components but in this case, "if it ain't broke..."

**Comment by pr1ntr** [comment]
I have another PR with implementing React DND, still WIP. But it makes working on this lib much easier IMO.

**Comment by bvaughn** [comment]
I see. I agree that the class syntax is easier to read, but I don't think the risk/value is there for a refactor just for stylistic preference.

FWIW though, `Async` is now class-based. Maybe gradually the others will be updated as well. 😄

In the meanwhile I'm going to close this PR.

**Pull request closed without merging**
