### PR TITLE
implemented optional rendering of arrow

### PR DESCRIPTION
**Pull request by rolandjohann**
This PR implements the ability to not render the arrow button by setting prop `arrowRenderer` to `null`. As the arrow element is responsible for the right padding a new less class has been introduced that will add right padding to the last element of the select control.

### CODE REVIEW

**Comment by rmmjohann** [comment]
Implements requested feature of #1700

**Comment by Uelb** [comment]
Is this PR going to be considered, 👍  on the request 😄 .

**Comment by rmmjohann** [comment]
@Uelb I'm afraid I don't understand.
Do I have to post a thumbs up emoji to mark the PR as ready to merge?

**Comment by tr0ythex** [comment]
Hi, guys, is that PR gonna be merged?

**Comment by JedWatson** [comment]
Sorry for the delay here - we've had another PR to do similar functionality (`arrowRenderer` can return `null`) but I've made the change to enable this as well.

**Comment by JedWatson** [comment]
Realised this PR includes updates to the less, docs and tests that weren't already present so I've resolved conflicts and merged it. Thanks @rolandjohann!

**Pull request merged**
