### PR TITLE
create css namespace

### PR DESCRIPTION
**Pull request by agutoli**
Way to specify css prefix `<Select {...props} cssPrefix="my-css-prefix" />`

### CODE REVIEW

**Comment by agutoli** [comment]
related issue #575

**Comment by agirton** [comment]
Hi @agutoli thank you for the PR. I'm not sure this is the route we want to go, but it's not something we want before 1.0 release. :smile:

**Comment by agutoli** [comment]
I perfect understand, thanks for your feedback. :)

**Comment by JedWatson** [comment]
Hey @agutoli sorry to decline this PR but I'm uneasy about introducing this complexity into the codebase at this point. To be honest, I really need to simplify things a bit so I and the other contributors have an easier time maintaining this package.

I'm also looking to move to a css-in-js solution in the next major version so that we don't have to maintain two separate stylesheet sources, which has been a real maintenance burden.

Thanks for the PR though - I really appreciate it 👍

**Comment by agutoli** [comment]
Hi @JedWatson, no problem at all. Actually it was like a suggestion and maybe is not a good moment like you said. 

I really like this package/component, but recently I was working for a project that I had some specifics needs, so I have created a package based on `react-select` but with `css-in-js` approach, shadowDOM, css-variables. I think it can be useful for you about this possible refactoring.

Node: This package has not the most of features of `react-select`, it`s like a concept (still alpha).

**Comment by JedWatson** [comment]
@agutoli sounds cool, feel free to drop a link here and I'll take a look!

**Comment by agutoli** [comment]
Ohh... haha sure... 
https://github.com/agutoli/react-styled-select

**Comment by agutoli** [comment]
complementiong: @JedWatsonI did a article about my "motivations" to write this pkg.
Original article: https://medium.com/trainingcenter/react-css-variables-shadowdom-styled-components-576f6c562d50 
Translated one (sorry about my bad english): https://medium.com/@agutoli/react-css-variables-shadowdom-styled-components-en-4a5f69b4b2f3

**Pull request closed without merging**
