### PR TITLE
Don't return null if the last item is manually removed

### PR DESCRIPTION
**Pull request by Mecit**
Fixes the `Invalid attempt to spread non-iterable instance` which occurs when items are removed from the input one by one.

### CODE REVIEW

**Comment by bladey** [comment]
Thanks @Mecit!

**Review by ebonow — CHANGES_REQUESTED** [review]
Great work. Perhaps you can add one small fix as well while this is open.

Can you add the following after line 34: (or something equivalent)

``` JS
if (value.find(val => val && val.value === inputValue)) return;
```

There is another bug present in this example if you try to add a duplicate word.

**Comment by Methuselah96** [comment]
Thanks for the PR! I believe this is better fixed by actually fixing the code instead of the docs (see https://github.com/JedWatson/react-select/issues/3632), but it makes sense to merge this until that is fixed.

**Review by ebonow — APPROVED** [review]

**Comment by Methuselah96** [comment]
Seems like the build is failing. Perhaps ESLint doesn't like the `??`?

**Comment by Mecit** [comment]
@Methuselah96 Yes, it seems [ESLint 7.2.0](https://eslint.org/blog/2020/06/eslint-v7.2.0-released#highlights) is needed for the nullish coalescing feature. If upgrading the package would be too bothersome, we can consider using || instead. `{ value: value || [] }` would yield the same result.

**Comment by Methuselah96** [comment]
@Mecit It's probably easier to go with `||` for now thanks! I'll work on getting ESLint upgraded in a separate PR.

**Comment by Methuselah96** [comment]
@Mecit This should actually be no longer necessary with the merge and release of https://github.com/JedWatson/react-select/pull/4339. Apologies for the back-and-forth on this and it no longer being necessary in the end. We really appreciate the contribution!

**Comment by Mecit** [comment]
@Methuselah96 no problem. I'm aware my commit was a quick fix to the problem and I'm glad the underlying issue was resolved in a more convenient way.

**Pull request closed without merging**
