### PR TITLE
Auto-update menu position when using menu portalling

### PR DESCRIPTION
**Pull request by Methuselah96**
Fixes https://github.com/JedWatson/react-select/issues/3533.
Fixes https://github.com/JedWatson/react-select/issues/4088.
Fixes https://github.com/JedWatson/react-select/issues/4159.
Fixes https://github.com/JedWatson/react-select/issues/4336.

This PR makes it so that when using menu portalling, event listeners are attached to the scrolling parents of the Select component in order to update the position after scroll or resize of one of its parents. This is accomplished using [Floating UI's `autoUpdate` function](https://floating-ui.com/docs/autoUpdate) and is heavily inspired by [their `useFloating` hook](https://floating-ui.com/docs/react-dom#usage) (but doesn't directly use it in order to make this more minor of a change).

Previously I was trying to rewrite all of menu positioning, but I decided to go with this more modest approach to get this resolved more quickly and make it less of a breaking change. However a complete rewrite of menu positioning might still happen in the future if proven necessary.

I attempted to make this change as backwards compatible as possible. The only change should be that there are event listeners attached to the Select component's scroll parents if using menu portalling. It could be argued that this is either a bug fix, a new feature, or a breaking change. My leaning would be to release this in a minor version since I can't think of a use case where one would not want the menu position to update when the Control element moves.

### CODE REVIEW

**Comment by ryan-castner** [comment]
@Methuselah96 I tried out this branch and while I am no longer having the menu render off screen, I am noticing with `menuPosition="auto"` that it is always positioning above when there is space to position it below:

image

**Comment by Methuselah96** [comment]
@ryan-castner Thanks for trying out the branch. I am not able to reproduce the issue you're experiencing. I've pushed a test of `menuPlacement="auto"` to https://github.com/JedWatson/react-select/tree/use-floating-with-test and get this result:

image

You can try it out by checking out that branch, starting the docs with `yarn start`, and navigating to `localhost:8000/cypress-tests`. Let me know if you can provide any more info regarding the issue you're experiencing.

**Review by lukebennett88 — APPROVED** [review]
This looks great @Methuselah96!
I couldn't replicate the issue that @ryan-castner mentioned.
I agree that a minor makes sense here 👍

**Review by jossmac — APPROVED** [review]

**Comment by Methuselah96** [comment]
This has been released in [`react-select@5.5.0`](https://github.com/JedWatson/react-select/releases/tag/react-select%405.5.0). We anticipate this change to be non-breaking which is why we're releasing it in a minor release, but if it turns out that this change is (non-trivially) breaking, it's possible we might revert the change and re-release it in a major version.

**Comment by alk-sdavid** [comment]
Hi @Methuselah96, thank you for this change, but I can confirm it's a major release which introduces some breaking change since it relies on `@floating-ui/dom` which relies itself on `ResizeObserver`. It breaks old browsers which does not support `ResizeObserver`. So I guess you should release it as version 6.0.0, and indicate this dependency in the changelog and the documentation.

Thanks again for your work and I hope it helps.

**Comment by Methuselah96** [comment]
@alk-sdavid Which browsers are you trying to support? As far as I know we don't have any browser support policy at the moment besides not IE 11 (mentioned in [the v5 upgrade guide](https://react-select.com/upgrade#from-v4-to-v5)).

**Comment by Methuselah96** [comment]
Looks like Safari on iOS 12.5 and Android Browser 4.4.4 might be the two browsers that don't support it if we're aiming supporting browsers with >.25% usage.

I've created https://github.com/JedWatson/react-select/pull/5381 to disable the `ResizeObserver` for now, and we can (potentially) re-enable it and make our browser support policy clear in the next major version.

**Comment by alk-sdavid** [comment]
Hi, yes it was not IE11, I just tested react-select on browserstack with some browser which does not support ResizeObserver (https://caniuse.com/resizeobserver). I do not have any issue about it, but I was just thinking it would be better to make a major release and to make it clear in the changelog and the documentation.
FYI, I noticed the ResizeObserver because some of my company unit tests failed because of it on a Dependabot pull-request, and then I dug a bit…

**Comment by kimi-truong** [comment]
Hi @Methuselah96, I've just upgraded to the latest version `v5.5.0` and all unit tests failed because of `ResizeObserver`
```
ReferenceError: ResizeObserver is not defined
```
Do you have any workaround on it?

**Comment by Methuselah96** [comment]
It should be resolved by https://github.com/JedWatson/react-select/pull/5381 which will hopefully be released in the next couple days.

**Comment by Methuselah96** [comment]
@alk-sdavid @kimi-truong This should be resolved in [`react-select@5.5.1`](https://github.com/JedWatson/react-select/releases/tag/react-select%405.5.1), let me know if you have any more issues.

**Comment by kimi-truong** [comment]
@Methuselah96 thanks so much 🙏 , it works now.

**Pull request merged**
