### PR TITLE
fix: lack of disabled attribute on select element causing color contrast issue

### PR DESCRIPTION
**Pull request by yhy-1**
As stated in this issue: https://github.com/JedWatson/react-select/issues/5550

"disabled" is properly set in the input, since it was used instead of aria-disabled, the lack of "aria-disabled" resulted in the automated a11y tool not determining it disabled element and cause a contrast issue. 

Ref: UIEN-3643

### CODE REVIEW

**Comment by yhy-1** [comment]
@jjuradok @AriPerkkio Hi, is there any maintainer who can review this PR, please?

CC: @mellis481

**Comment by mellis481** [comment]
This is a glaring a11y failure ([WCAG 1.4.3](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html) my team is very much hoping can get merged and released soon.

**Comment by edmilicich** [comment]
@jjuradok lo va a ver, tranqui

**Comment by yhy-1** [comment]
@edmilicich , @jjuradok 
Any new update?

**Review by jjuradok — APPROVED** [review]

**Comment by yhy-1** [comment]
@lukebennett88 Hi, are you able to look at this and get a merge or a list of approving reviews with write access?

**Review by mellis481 — APPROVED** [review]

**Review by lukebennett88 — APPROVED** [review]
Thanks so much for the PR, really great to see folk who care about accessibility 🙌

**Pull request merged**
