### PR TITLE
[V2] docs love

### PR DESCRIPTION
**Pull request by jossmac**
DO NOT MERGE: more coming...

### CODE REVIEW

**Comment by JedWatson** [comment]
@jossmac is this good to go yet? cypress is failing on a test, looks pretty minor. Happy to clean that up if this is otherwise good to bring back into the `v2` branch

**Comment by jossmac** [comment]
@JedWatson nearly there. Give us an hour to clean it up a bit:

- Fix the tests
- Remove routes w/o content
- Clean up the header a bit

**Comment by jossmac** [comment]
@JedWatson sorted

**Comment by JedWatson** [comment]
Looks great, @jossmac 😁

**Pull request merged**
