### PR TITLE
added inputValue property

### PR DESCRIPTION
**Pull request by vzaidman**
fixed #669

### CODE REVIEW

**Comment by vzaidman** [comment]
so now you can pass 
<state 
  inputValue={this.state.inputValue}
  onInputChange={ this,setState({ inputValue, isLoading:true }) }
/>

**Comment by wereHamster** [comment]
This seems like a really useful and straightforward change. What's the holdup?

**Comment by mmmveggies** [comment]
Do you think you could rebase this PR?
If not, I will open a new one - this would make using `<Select.Async />` better when having large result sets because `loadOptions` gets called with `''` when the component re-mounts, so if your selection is from a query that starts with `xx` the `value` does not match up with the new `options` and the placeholder is displayed, which is erroneous.

**Comment by vzaidman** [comment]
I didn't use this library for a long time and don't remember what's going here.

**Pull request closed without merging**
