### PR TITLE
Fix menu closing when click outside the menu box

### PR DESCRIPTION
**Pull request by ytiurin**
This refers to the issue https://github.com/JedWatson/react-select/issues/2239

### CODE REVIEW

**Comment by vitorhorta** [comment]
Is this PR merged? Looking forward for this fix!

**Comment by lifejuggler** [comment]
I was wondering when this will be merged in?

**Comment by eugensunic** [comment]
It has been merged. Just put the latest version in your package json

On Feb 22, 2018 17:17, "Tom Choi" <notifications@github.com> wrote:

I was wondering when this will be merged in?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/JedWatson/react-select/pull/2314#issuecomment-367733427>,
or mute the thread

**Comment by jboelen** [comment]
@eugensunic Looks like this was approved but not merged?
https://github.com/JedWatson/react-select/blob/master/src/Select.js#L205-L219

**Comment by eugensunic** [comment]
It was merged use 1.2.1 in package json and run npm install

**Comment by jboelen** [comment]
Sorry if I'm missing something, but the commit that corresponds to version 1.2.1 shows that the lines remain unchanged. 

https://github.com/JedWatson/react-select/blob/82910d9225f7aff73ac5052da9dc1e7f52f13de7/lib/Select.js#L251-L265

I've also checked the source from npm for v1.2.1, and it shows the same unchanged lines.
> node_modules/react-select/dist/react-select.es.js
image

**Comment by vitorhorta** [comment]
@jboelen did you get any news on this PR? Still not merged here.

**Comment by abstract071** [comment]
I had trouble with closing select. The problem was that I set display: none to input element under react select. After removing this the behavior became ok.
Maybe it will be helpful for someone :)

**Comment by willmore** [comment]
@jboelen @ytiurin despite [comments](https://github.com/JedWatson/react-select/pull/2314#issuecomment-367774513) stating this has merged, it appears otherwise.

Is there an ETA on merging? Thank you.

**Comment by RocketPuppy** [comment]
We are also looking for this to be merged.

**Comment by abraham-chan** [comment]
ping @eugensunic PR approved but not merged/released?

**Comment by RealSilo** [comment]
Could you pls merge this?

**Comment by willmore** [comment]
@JedWatson appealing to you as the project owner. How do we get this merged in a "timely" manner? In general, what should be the expected time between reviewer approval merge? Thank you.

**Comment by JedWatson** [comment]
I do realise that stronger guidelines for issues and PRs would help clarify why this is waiting, and result in less frustration and better quality contributions over all. I'll try and set that up in the future.

I'm also sure there are a lot of open issues and PRs that would benefit from this kind of clarity, and if anybody wants to help me manage that it would be really helpful.

**Comment by ytiurin** [comment]
Hi guys, more details about this commit from my side. The component menu closes on input blur, but doesn't close in case when input field is not used in the component. I think there was a code some time before, to handle no-input menu closing because we have this code for touch outside menu. So this commit handle situation when there is no input element visible on screen.

**Comment by willmore** [comment]
>I'm also sure there are a lot of open issues and PRs that would benefit from this kind of clarity, and if anybody wants to help me manage that it would be really helpful.

Thank you for your comments @JedWatson! I will ask members of my team whether they are interested and able to contribute.

**Comment by jossmac** [comment]
Thanks @ytiurin 🙂

**Comment by TheSharpieOne** [comment]
This change appears to have broken the `closeOnSelect={false}` functionality of v1. since the mousedown listener will fire the `handleTouchOutside` and always determine that the target is not within the wrapper (since the target is removed from the DOM), it will always fire `this.menuClose()`.

**Pull request merged**
