### PR TITLE
Export the Value component

### PR DESCRIPTION
**Pull request by Grahack**
Or is there a way to pre-fill the Creatable component with known values?

### CODE REVIEW

**Comment by Grahack** [comment]
Sorry, I managed to pre-fill the component with an array of strings. I only missed `multi={true}`.

**Comment by sakulstra** [comment]
@Grahack why did you close this pull request? I actually wanted to commit exactly the same one right now :dancer: 

Exporting Value would allow us to write valueComponent without rewriting everything from scratch:
```
import {Value} from 'react-select'

class ValueComponent extends Value{
render () {
const title = generateTitle(this.props.value)
		return (
			<div className={classNames('Select-value', this.props.value.className)}
					 title={title}
			>
				{this.renderRemoveIcon()}
				{this.renderLabel()}
			</div>
		);
	}
}
```

**Comment by Grahack** [comment]
Because I don't need it anymore. I can reopen it for you.

**Comment by JedWatson** [comment]
👍 thanks @Grahack

**Pull request merged**
