### PR TITLE
call `this.autoloadAsyncOptions()` into `componentDidMount()`

### LINKED ISSUE #279: `autoload={true}` doesn't call `asyncOptions` handler
Code example:

```
<Select
          {...this.props}
          value={this.state.value}
          asyncOptions={this._getOptions}
          onChange={this._handleChange}
          autoload={true} />
```

(NOTE: I use ES7 async/await into `this._getOptions`)

### PR DESCRIPTION
**Pull request by iam4x**
Call `this.autoloadAsyncOptions()` into `componentDidMount()`

see:
  * https://github.com/JedWatson/react-select/issues/279
  * https://github.com/facebook/react/issues/1740

(fixes #279)

### CODE REVIEW

**Comment by iam4x** [comment]
poke @JedWatson this is 100% working you can merge eyes closed :+1:

**Comment by JedWatson** [comment]
@iam4x not totally eyes closed, the changes are in `lib` not `src`, mind resubmitting with changes to the right file? (see contributing guide for explanation)

:+1: otherwise

**Comment by iam4x** [comment]
@JedWatson Sorry, it's all good now. (I also fixed a little codestyle error thrown by eslint)

**Comment by JedWatson** [comment]
Thanks @iam4x!

**Pull request merged**
