### PR TITLE
feat(pagination): add async pagination

### LINKED ISSUE #644: [Question] Load on scroll/pagination
Hello.

I would like to know if react-select supports pagination on scroll like (for example) select2: https://select2.github.io/examples.html#data-ajax

Thank you for your attention.

### PR DESCRIPTION
**Pull request by TheSharpieOne**
This checks the first box in [this list for v1.0.0](https://github.com/JedWatson/react-select/issues/568#issuecomment-153785740) and closes #644

This adds a new `pagination` prop to the `Select.Aync` component. It is a boolean which is `false` by default (`false`: things act as they did before it was added). When `pagination` is `true` `loadOptions` is given an additional argument; `page`.
`page` tells the user's `loadOptions` function which page to load (they can use to when building their request). Additional page results are appended to the options list. Changing the input value will reset the page back to `1`.
`loadOptions` is called when the user scrolls to the bottom of the menu list, trigger the next page of results to be appended.
Caching is used! (Cache all the things!). If a user scrolls down enough to load additional pages, then changes the input (triggering new requests), then enters the original input, all of the pages for the original input will be loaded back and when the user scroll to the bottom again, it will pick up on the page it left off on.

Documentation has been updated to reflect the new prop and how it affects loadOptions' signature.

EDIT:
async-pagination

### CODE REVIEW

**Comment by syndbg** [comment]
A separate callback prop `pageChange` would be super useful and needed if a developer would like to use debouncing on input change (currently `loadOptions`) and no debounce on `pageChange`.

**Comment by TheSharpieOne** [comment]
Rebased to fix conflicts. @JedWatson or someone please review before it conflicts again or just gets lost in the pile. This feature is on the roadmap to v1.

@syndbg you can use the `page` argument to determine debounce or not to debounce. For instance, say you have a function which fetches the options, we'll call it `fetchOptions`, and you use something like lodash's debounce to get a new function, we'll call it `waitnFetchOptions` (this is pretty standard so far for a typical debounce setup). You can have a third function which is passed the `Select.Aync` as the `loadOptions` props which, based on the page argument calls `waitnFetchOptions` or `fetchOptions` like so:
```
function loadOptions (inputValue, page, callback) {
  if (page > 1) {
    fetchOptions(inputValue, page, callback);
  } else {
    waitnFetchOptions(inputValue, page, callback);
  }
}
```
It's a simple function, and since debouncing has been left to the user of the library to implement (in user-land), It is probably best to leave this in user-land as well.

**Comment by lucaas** [comment]
Thank you for your contribution, we would love pagination support for react-select.

Our API works with an `offset` parameter which is returned with the payload (as `next_offset`). This can not be simply calculated from a page argument (`offset = page * pageSize`), as items may be culled from the returned result.

We would like to save the `next_offset` value, and pass that in to `loadOptions`. Could this use case be supported?

**Comment by TheSharpieOne** [comment]
Rebased once again to remove conflicts....

@lucaas that is a pretty specific use case. The problem is, react-select's async doesn't know anything about the call or the response, only the options you pass to it. Meaning your code handles making the call and parsing the response. You could technically store that value in your code.

I do see this use case in things like AWS's dynamodb, where all you get is a pointer to where it left off from last time and thus, where to start from in the next query/page.

I'm not 100% sure what a clean implementation for this would look like. The callback does currently accept an object. It only looks for and uses the `options` key/property in the object. Another property could be passed in that object which would just be returned/sent the next time `loadOptions` is called. That value would need to be stored in the component's cache (if enabled) so it can be picked up where it left off when the input changes and changes back.

Honestly, after almost a month and 2 rebases to resolve conflicts, I don't think this feature will get merged anyways, but I'd love for some input from a collaborator about adding the offset/pointer.

**Comment by TheSharpieOne** [comment]
Instead of me trying to keep this PR from conflicting by rebasing all of the time just for it to conflict again after another week of sitting here... Just let me know when you are ready for this feature and I will rebase then.

**Comment by syndbg** [comment]
@JedWatson can you take a look at this?

**Comment by LordSputnik** [comment]
@JedWatson this is something we'd really like to see in react-select too, let me know if there's anything that can be done to help get it in!

**Comment by dziulius** [comment]
Just merge this already. It's really annoying to use repo from github and maintain it by my self.

**Comment by rodrigoapereira** [comment]
@JedWatson Is there anything still pending for this to be merged?

We are using this, and this is working fine.

**Comment by nancruz** [comment]
@JedWatson My team, at work, has been waiting for a while for this feature. Is there anything holding you back from merging this feature?

**Comment by syndbg** [comment]
@JedWatson It's about time to make something regarding this PR. How can we help to get this merged?

**Comment by nivek91** [comment]
@JedWatson anything I can do to help? Thanks

**Comment by nivek91** [comment]
@TheSharpieOne  I've testing your example and it doesn't work to me. When I get to the latest element, the second page is not being requested (just cloned your repo)

image

**Comment by TheSharpieOne** [comment]
Here is what I see
async-pagination

Can you show what you are doing?

**Comment by nivek91** [comment]
I'm on windows, branch feature/async of your repo, doing the same..
vid

**Comment by TheSharpieOne** [comment]
I am on mac, branch feature/async<b>-pagination</b> of my repo (but I believe that is what you meant)
It looks like windows is probably not firing off the scroll bottom trigger. I don't have a windows machine right now. Can you drop a breakpoint [here](https://github.com/TheSharpieOne/react-select/blob/feature/async-pagination/src/Select.js#L548) and see if it get triggered or if something funky is going with the values that determine if the menu is at the bottom or not.

**Comment by nivek91** [comment]
yes, thats the branch, here is the breapoint:

if you want I can share my screen to troubleshoot it:
bottom

**Comment by TheSharpieOne** [comment]
Definitely looks like something funky with the numbers not adding up. 
This was/is code that is already in the codebase and is not part of my changes. That doesn't mean I can't fix it. Probably just need to do some rounding.

**Comment by nivek91** [comment]
Any idea how to fix it? 👍

**Comment by fzzzt** [comment]
👍 The lack of this feature is keeping us from using this component.

**Comment by glentakahashi** [comment]
@nivek91 i assume this is the error with scrolling https://github.com/JedWatson/react-select/pull/785/files

**Comment by agirton** [comment]
Hi @TheSharpieOne, thank you so much for your patience. I've checked over the code and this looks good to me. I've also tested this in the major browsers (minus Edge/IE). 

In regards to the demo, I think it would make more sense to add this to the Github example and then make pagination a checkbox, just like multi.

I'd really like to get this in and then finally have a 1.0 release. Let me think about this, just want to make sure we have all the bases covered.

**Comment by TheSharpieOne** [comment]
@agirton I can change the example and rebase (again) to resolve the new conflicts when I get some time. As pointed out by others, there is an issue with Windows. It is not so much with the changes made by this PR, but with an existing method; `handleMenuScroll` via the `onMenuScrollToBottom` prop in Select.js (not Async.js). There is a separate PR to address that (linked in other comments; haven't looked at it).

**Comment by VladimirPal** [comment]
@TheSharpieOne Thank you for the PR, i've checked and it works, but i think you need to prevent scroll event until all pages didn't loaded.

I've created builded version of your branch, if someone wants to use it with npm until it didn't merged:
https://github.com/web-pal/react-select/tree/feature/async-pagination
in package.json: 
`    "react-select": "git://github.com/web-pal/react-select.git#feature/async-pagination",
`

**Comment by TheSharpieOne** [comment]
@VladimirPal I not sure what you mean, but if you are talking about how it scrolls the page when it reaches the end of the list, that is a separate concern with separate open issues and pull request as it is it specific to this enhancement, but an existing issue.

**Comment by VladimirPal** [comment]
@TheSharpieOne That's exactly what i meant. Thanks.

**Comment by goodwill** [comment]
Any reason why this can't be merged? TBH this is very disappointing when people said this can replace select2 while there are such a crucial feature missing.

**Comment by rostero1** [comment]
@VladimirPal are you waiting for the scroll end issue to be resolved?  Also, are you suggesting https://github.com/web-pal/react-select/tree/feature/async-pagination until then?

**Comment by jxom** [comment]
@JedWatson - this would be great. :)

**Comment by LordSputnik** [comment]
@JedWatson, @agirton, @TheSharpieOne - this looks so close to being ready to merge. Is there a chance of having a final push and getting this popular feature request released soon? What remains to be done?

Many thanks for all your hard work and effort so far!

**Comment by TheSharpieOne** [comment]
@LordSputnik the only thing I know that is left to be done the merge button to be clicked.

**Comment by VladimirPal** [comment]
@rostero1 I'm not the person who decides future of this PR, ask @JedWatson

**Comment by chrisv2** [comment]
@TheSharpieOne nice work, thanks a lot. Just a minor improvement: Since there is already a [`complete` flag](https://github.com/JedWatson/react-select#async-options) indicating that there are no more results, this could be used as well instead of always requesting the next page. But that's not critical, of course.

FWIW, I've created a repo which also contains the compiled files [here](https://github.com/greybyte/react-select/tree/feature/async-pagination), so anyone who wants to use this excellent feature before it gets merged can do it like this:

```bash
yarn add https://github.com/greybyte/react-select.git#feature/async-pagination
# - or -
npm install https://github.com/greybyte/react-select.git#feature/async-pagination
```

**Comment by TheSharpieOne** [comment]
@chrisv2 the `complete` flag doesn't actually exist. I am not too sure if documentation is out of date or if it is a defect.
Search the current codebase for "complete" and you will not find it in any code (just MD files and an example). There are issues (such as #1514) saying it is not working.
It looks like it was removed by [this commit](https://github.com/JedWatson/react-select/commit/ed8d087d4d5d1c46b0b1f7a11c71eb3949be5dd1#diff-149b30fde0306e461dc519d4853f1e50L24) by and never added back. The commit was by @bvaughn and mentioned "Cache not yet implemented. Pushing for discussion" (another commit later added caching. Maybe the discussion resulted in removing `complete`?)

**Comment by ahyanarizky** [comment]
I hope this super cool feature can be merged in short time ! 😄

**Comment by tatiana9** [comment]
Hi, I'm very interested in this cool feature but just one quick question:

In my app, I need to be able to set an initial value for the select box (I use react-select in multi select mode). However if that initial value has an option that does not appear in the first page of options (which is fetched by default by `loadOptions`), it is not displayed as selected until I scroll down enough so that this option finally gets fetched and appears in the list of options.

Is this pagination feature still supposed to support the setting of an initial value (through the `value` prop) ? Would that mean that `react-select` has to support setting an initial value that does not match the options ?

**Comment by VladimirPal** [comment]
> Is this pagination feature still supposed to support the setting of an initial value (through the value prop) ? Would that mean that react-select has to support setting an initial value that does not match the options ?

I think the problem not in initial value, initial value works, but react-select can't find this value in his current options, because it didn't download it yet.
I've faced with same issue and until developers didn't handle it(or maybe they have solution, at least i don't know) i've created a fast fix, just added prop `handleUnknownValue` which accept function that will be called when react-select will have a value that can't find in his options, this function must return option(because if you give this value you have an option object too).

You can find't here - https://github.com/web-pal/react-select/commit/52edc6a8aa5474a8eb9cdbade20ac0f5e43c6b5f

You can install with with npm, i've typed about it:
>I've created builded version of your branch, if someone wants to use it with npm until it didn't merged:
https://github.com/web-pal/react-select/tree/feature/async-pagination
in package.json:
"react-select": "git://github.com/web-pal/react-select.git#feature/async-pagination",

**Comment by tatiana9** [comment]
Thanks for your answer @VladimirPal ! Indeed this is my issue.

I was initially using @chrisv2 's repo https://github.com/greybyte/react-select.git#feature/async-pagination

While installing your repo instead in order to try your solution, I realized that I was using react-select in the `simpleValue` mode (which stores only the option's key in the `value` prop, or in the mutli case, a comma separated list of keys) so I had no way of knowing what to return from `handleUnknownIssue` as an option label without having the full option already at hand.
So I changed my code to not use the `simpleValue` mode anymore, and I found out that initial selection of not-yet-downloaded options are displayed correctly, without needing to implement `handleUnknownIssue`... I am not sure why at this stage but I thought I should let you know. I am back to using @chrisv2 's repo and the initial values work correctly.

**Comment by danreeves** [comment]
Is there anything I can do to help speed up the release of this feature?

**Comment by olegBryukhanov** [comment]
Is this feature merged? Where can I see an official example for this?

**Comment by TheSharpieOne** [comment]
@olegBryukhanov all of the PRs in the project have previews which automatiocally get deployed. You can get to the preview using the "deploy/netlify" "details" ling in the "checks" section
image

**Comment by olegBryukhanov** [comment]
@TheSharpieOne Can i download thi build as NPM package?

**Comment by xizi-xu** [comment]
Any update on this?

**Comment by louisemccomiskey** [comment]
Hi I'm also wondering if there is an update to when this will be ready please?

**Comment by TimNZ** [comment]
@JedWatson can you spare 30 seconds illuminating us why you haven't merged this, or even engaging with the conversation?

**Comment by horaciosystem** [comment]
Hi @JedWatson, we all miss you. Could you please take a look on that, there's a lot of people waiting for it.

**Comment by ptahchiev** [comment]
+1 for this - I'd really like to see this merged :)

**Comment by paulocesarpcfj** [comment]
Please, could you merge this PR? Its really important to have this.

**Comment by daino3** [comment]
Would reallllllllly love this PR. Can we please get some attention on this? We're currently trying emulate this behavior with our own state / getOptions function...

🙏 📿

**Comment by nafg** [comment]
https://github.com/vtaits/react-select-async-paginate works

**Comment by rghose** [comment]
Wow its been two years now! @TheSharpieOne seems like an issue with deploy..

**Comment by TheSharpieOne** [comment]
Closing this as at this point it never going to get merged. I'll reopen if a maintainer chimes in stating otherwise.

**Comment by ap47** [comment]
Reopen this!!!

**Comment by TheSharpieOne** [comment]
development has moved on. This was for pre-1.0, it's now on 3.0 with a complete rewrite. The PR was open for over 2 years, it's never going to merge.

give https://github.com/vtaits/react-select-async-paginate a try.

**Comment by phazei** [comment]
Pretty sad that it's been asked for so much and there was so much work put into this PR and @JedWatson never even bothered saying anything about it and here we are years later and it's still not a feature.

**Pull request closed without merging**
