### PR TITLE
Manually set 'isLoading' state for async selects

### LINKED ISSUE #2986: [v2] No way to manually set isLoading on async select box
So I'm using the isLoading prop on the normal Select to show a loader in the select box after you select something while it is fetching data to populate some fields below.

Somewhere else in the app I am trying to do the same with the async select component and it doesn't seem to work, I think it should be possible to override the isLoading prop.

### PR DESCRIPTION
**Pull request by csilkwor**
Fixes #2986

### CODE REVIEW

**Comment by csilkwor** [comment]
There is a related pr already open for this issue, but it has been dormant and sitting with a merge conflict for a few months.

It is necessary for my use case to be able to explicitly set the loading property of an asynchronous select. This change keeps the current functionality intact while allowing the loading indicator to be displayed at the discretion of the developer.

**Comment by comfroels** [comment]
@JedWatson Is it possible for someone to maybe take a look at this?

**Comment by oudoulj** [comment]
I have an Async select and would like to **always** hide the _"Loading..."_ and the _3 dots_ on the right while typing and there is no result yet.
How do I do that ?
Thanks!
Async select

**Comment by oudoulj** [comment]
> I have an Async select and would like to **always** hide the _"Loading..."_ and the _3 dots_ on the right while typing and there is no result yet.
> How do I do that ?
> Thanks!
> Async select

I am replying to myself.
I was able to hide both the Loading indicator and its 3 dots on the right by using the styles mentioned [here](https://react-select.com/styles)
Something like that :
```
<AsyncSelect
        ...
        styles={myStyles}
/>

export const myStyles = {
        ...
        loadingIndicator: () => {
		return {
			display: "none"
		};
	},
	loadingMessage: () => {
		return {
			display: "none"
		};
	}
};
```

**Comment by RobertDaleSmith** [comment]
@JedWatson Please merge. I could really use this so that I can show the loading indicator on AsyncCreatableSelect while onCreateOption is fetching.

**Comment by JedWatson** [comment]
Looks good, thanks @csilkwor! sorry for the delay merging. Will ship with the next release!

**Comment by Mujaddadi** [comment]
I am still facing this issue. Not sure it is released yet or not.

**Comment by sirjuan** [comment]
Could this please be released @JedWatson?

**Comment by laznic** [comment]
@JedWatson could you do a release with this fix included please?

**Comment by makker** [comment]
It would be greatly appreciated if this could be be released. Thanks for the awesome work with the project!

**Comment by mika-kaki** [comment]
This fix would be greatly appreciated! Thanks for a great project!

**Comment by yannbriancon** [comment]
I agree with all the previous comments, I'd love to see this released! 
Always cool to work with this project!

**Pull request merged**
