### PR TITLE
Trigger onInputChange on clear

### PR DESCRIPTION
**Pull request by phamthaibaoduy**
I'm using Async component, when I click on clear button, list of options is not reloaded with empty string. Which is IMO a little bit strange.

### CODE REVIEW

**Comment by plantvsbirds** [comment]
an empty string is probably not good, since there are people who also use object as options. what about just `undefined`?

**Comment by phamthaibaoduy** [comment]
@plantvsbirds sorry but it is onInputChange, not onChange

**Comment by plantvsbirds** [comment]
my bad :)

**Comment by gwyneplaine** [comment]
@phamthaibaoduy, can you confirm that the bug you're fixing is still, reproducible with the current rc of react-select? 

At the moment clearValue calls `this.handleInputValueChange` with an empty string, which in turn invokes this.props.onInputChange with the passed in value. So the additional onInputChange here is seemingly redundant.

Unfortunately, I have been unable to reproduce this on my end, PR closed until further notice

**Comment by phamthaibaoduy** [comment]
Sorry for late response, did you check this issue yourself?

**Comment by phamthaibaoduy** [comment]
I checked code in rc10, look like the issue is fixed. Thank you @gwyneplaine

**Pull request closed without merging**
