### PR TITLE
[Feature] built-in debounce support on async select

### PR DESCRIPTION
**Pull request by mmuller99**
[#3075](https://github.com/JedWatson/react-select/issues/3075)
[Proposal](https://github.com/JedWatson/react-select/issues/614#issuecomment-367715672)

`loadOptions` is debounced by prop `debounceInterval`, minimizing unnecessary calls.
Initial load unaffected.

Example:

`loadOptions` only called after 250 milliseconds

```jsx
<AsyncSelect 
      defaultOptions
      loadOptions={loadOptions}
      debounceInterval={250}
/>
```

### CODE REVIEW

**Comment by dustinsoftware** [comment]
@mmuller99 pretty cool, but this seems to introduce a new problem when mixing Async with Creatable: The "New entry" indicator flashes briefly before the search happens. GIF recording below:

react-select-async

**Comment by mmuller99** [comment]
@dustinsoftware thanks for the feedback.  I have a feeling its to do with "allowCreateWhileLoading", will have a look.

**Comment by mmuller99** [comment]
So yes, setting
```jsx
allowCreateWhileLoading={false}
```
stops the behaviour as expected.

**Comment by dustinsoftware** [comment]
It looks like the problem can be avoided by debouncing the `loadOptions` method instead:

```jsx
constructor(props: Props) {
	super();
	this.loadOptions = props.debounceInterval
		? debounce(this.debouncedLoadOptions, props.debounceInterval)
		: this.debouncedLoadOptions;
}

debouncedLoadOptions = (inputValue: string, callback: (?Array<*>) => void) => {
	// same method contents, but the method name is renamed to avoid confusion
};

render() {
	return (
		<SelectComponent
			// other props
			onInputChange={this.handleInputChange}
		/>
	);
}
```

**Comment by gsinovsky** [comment]
any chance on an update on this? glad to help if needed @mmuller99

**Comment by mmuller99** [comment]
@dustinsoftware thanks for the pointer, I debounced the loadOptions instead.

It has been expressed that the owner wants the debounce to be left to the users [here](https://github.com/JedWatson/react-select/pull/473#issuecomment-347172715).

Maybe one of the collaborators can express their opinion on this PR?

**Comment by gsinovsky** [comment]
Hi @JedWatson, any chance on reviewing and merging this?

**Comment by mmuller99** [comment]
@gwyneplaine any feedback?

**Comment by gsinovsky** [comment]
@JedWatson @mmuller99 still very interested in seeing this merged and published.

**Comment by gwyneplaine** [comment]
@mmuller99 definitely haven't forgotten about this PR, will be looking into this more deeply as part of our work to refactor async select. Will have a deeper look at this as soon as I have more time on my hands :) thanks for your patience

**Comment by chrysb** [comment]
Strong +1 to this feature request

**Comment by filippoitaliano** [comment]
There's a plan to merge this feature soon?

**Comment by ramospedro** [comment]
This is just what I need in my current project!
Any news on this?

**Comment by bluefire2121** [comment]
It's nearly November 2019...is there an update yet?

**Comment by gsinovsky** [comment]
Please! Let it be one

Gustavo Siñovsky
Software Engineer

**Comment by hnhegde** [comment]
Any update on this PR? After using AsyncSelect, it is apparent that debounce must be a necessary accompaniment to AsyncSelect.

**Comment by JoeDuncko** [comment]
Any updates? This is 100% a required feature for async select.

**Comment by papaiatis** [comment]
It's a long awaited async feature for `react-select`! Would be great to get it merged now.
@gwyneplaine could you post an update this community please?

**Comment by balazs-endresz** [comment]
FWIW, this can be also done currently with a function that takes a promise and returns a debounced promise (but not with any ordinary debounce functions):  https://gist.github.com/balazs-endresz/c0c814a513724f44d90265422b9ae530 Call this outside a component or with `useCallback` and pass the result to `loadOptions`. And I think we've had issues with `cacheOptions` as well, so optionally this does something like that too.

**Comment by khaphannm** [comment]
Any updates???????? Really needed :D

**Comment by mmuller99** [comment]
@bladey


1xg4u8

**Comment by Methuselah96** [comment]
I've started [a fork](https://github.com/react-select-oss/react-select) of react-select. Feel free to resubmit this PR on the fork and we can get it merged and released.

**Comment by ochov1** [comment]
> [#3075](https://github.com/JedWatson/react-select/issues/3075)
> [Proposal](https://github.com/JedWatson/react-select/issues/614#issuecomment-367715672)
> 
> `loadOptions` is debounced by prop `debounceInterval`, minimizing unnecessary calls.
> Initial load unaffected.
> 
> Example:
> 
> `loadOptions` only called after 250 milliseconds
> 
> ```js-jsx
> <AsyncSelect 
>       defaultOptions
>       loadOptions={loadOptions}
>       debounceInterval={250}
> />
> ```

this is not working at all

**Comment by ebonow** [comment]
Greetings,

@JedWatson has expressed the following opinion https://github.com/JedWatson/react-select/pull/473#issuecomment-347172715

> Thanks for the PR but I'd prefer this was left for users to implement in the function that's passed to loadOptions
> 
> You can do this really simply by wrapping the method in lodash's debounce method (or similar) without adding any more logic to react-select

For those looking for a solution, please feel free to try the solution suggested here: https://github.com/JedWatson/react-select/issues/614#issuecomment-679056254

``` js
const loadOptions = React.useCallback(
  debounce((inputValue, callback) => {
    getOptions(inputValue).then(options => callback(options))
  }, 500),
  []
);

return <AsyncSelect loadOptions={loadOptions} {...otherProps} />
```

Demo: [codesandbox](https://codesandbox.io/s/react-select-async-debounce-usecallback-oeixm)

**Comment by JedWatson** [comment]
Hey everyone, and thanks for the PR @mmuller99

Sorry for the lack of comms here, below is my response but I also want to acknowledge that this should have been said much earlier.

My view on this is that it is something you can (reasonably) easily do outside of react-select when you need it, and many libraries exist already specifically to make debouncing function calls easy.

As we've seen from the challenging history maintaining the library, even simple features add to the already huge surface area so the bar for inclusion of anything that can be done "in user-land" is really high.

**However** talking through it with @ebonow and @Methuselah96 in our maintainers sync this week, the combination of these points have gotten it over the line:

* How often would you use `Async` and not want to debounce? It seems like the answer is "not often"
* There is a really high level of community support for adding this
* The additional feature is just scoped to the Async component

We're in the middle of our TypeScript conversion now (#4489) so this PR won't go in directly, but we'll backlog adding this for a post-5.0 release

**Comment by mmuller99** [comment]
Thank you @JedWatson , appreciate the in-depth response and that native `debounce` is finally on the roadmap.

**Comment by mrtk0y** [comment]
> Greetings,
> 
> @JedWatson has expressed the following opinion [#473 (comment)](https://github.com/JedWatson/react-select/pull/473#issuecomment-347172715)
> 
> > Thanks for the PR but I'd prefer this was left for users to implement in the function that's passed to loadOptions
> > You can do this really simply by wrapping the method in lodash's debounce method (or similar) without adding any more logic to react-select
> 
> For those looking for a solution, please feel free to try the solution suggested here: [#614 (comment)](https://github.com/JedWatson/react-select/issues/614#issuecomment-679056254)
> 
> ```js
> const loadOptions = React.useCallback(
>   debounce((inputValue, callback) => {
>     getOptions(inputValue).then(options => callback(options))
>   }, 500),
>   []
> );
> 
> return <AsyncSelect loadOptions={loadOptions} {...otherProps} />
> ```
> 
> Demo: [codesandbox](https://codesandbox.io/s/react-select-async-debounce-usecallback-oeixm)

i tried this but the loadOptions didn't wait for the response, and won't re-render options when data is ready

**Comment by mrtk0y** [comment]
> Greetings,
> 
> @JedWatson has expressed the following opinion [#473 (comment)](https://github.com/JedWatson/react-select/pull/473#issuecomment-347172715)
> 
> > Thanks for the PR but I'd prefer this was left for users to implement in the function that's passed to loadOptions
> > You can do this really simply by wrapping the method in lodash's debounce method (or similar) without adding any more logic to react-select
> 
> For those looking for a solution, please feel free to try the solution suggested here: [#614 (comment)](https://github.com/JedWatson/react-select/issues/614#issuecomment-679056254)
> 
> ```js
> const loadOptions = React.useCallback(
>   debounce((inputValue, callback) => {
>     getOptions(inputValue).then(options => callback(options))
>   }, 500),
>   []
> );
> 
> return <AsyncSelect loadOptions={loadOptions} {...otherProps} />
> ```
> 
> Demo: [codesandbox](https://codesandbox.io/s/react-select-async-debounce-usecallback-oeixm)

i tried this but, the options won't be re-render when the data is ready
any solution for this sir ?

**Comment by ebonow** [comment]
With version 5 out, I think we are in a position to pick this up if someone is willing to put in the work to have this work converted to the new TypeScript rewrite.

It seems reasonable that this is only applied to AsyncSelect and not Select correct?

**Comment by lvidal1** [comment]
Hi, is there any update on this?

**Comment by dcousens** [comment]
The pull request as written doesn't have consensus, and I think for now the recommendation of debouncing the `loadOptions` call yourself is transparent and easy.

I think patterns like these are incredibly difficult to know where to draw the line between convenience and, for the maintainers, trying to minimize the amount of responsibility that `react-select` takes on.
This feature might come back into the fold in a near future, but for now, I'm going to close this pull request.

**Pull request closed without merging**
