### PR TITLE
Add placeholderOnOpen prop to view placeholder onOpen

### PR DESCRIPTION
**Pull request by athomann**
Add placeholderOnOpen prop to view placeholder onOpen.  Some users didn't realize the dropdown was a typeahead because the value was still showing.  This PR adds an option to be able to show the placeholder when `isOpen` to allow instructions to be shown.

### CODE REVIEW

**Comment by JedWatson** [comment]
Thanks for the PR @athomann!

Could you resolve the conflicts please? you don't need `React.` now, we've upgraded to the `prop-types` package.

Also, let's call this prop `displayPlaceholderWhenOpen` for clarity

**Comment by athomann** [comment]
Done!

**Comment by Drecula** [comment]
I monkey patched this to handle the negative case

`	if (!valueArray.length || this.props.displayPlaceholderWhenOpen && isOpen) {
			if(!this.state.inputValue && !this.props.displayPlaceholderWhenOpen && isOpen) return null
			return !this.state.inputValue ? _react2['default'].createElement(
				'div',
				{ className: 'Select-placeholder' },
				this.props.placeholder
			) : null;
		}`

**Comment by TallOrderDev** [comment]
I don't think this is documented on the ReadMe

**Comment by TallOrderDev** [comment]
@athomann @JedWatson ^^^^

**Comment by carlosbensant** [comment]
**Floating Label:**
I'd like to create a Floating Label theme of this package (just using CSS), but it expects the placeholder to persist along with the current value.

The **displayPlaceholderWhenOpen** prop is an outstanding option for what I'm expecting to see.

When are you expecting to merge this?

**Comment by JedWatson** [comment]
@carlosbensant this change still won't actually do what you want, because the placeholder will still disappear when the user types in the input

@athomann sorry for dropping this one, got overwhelmed by issues and PRs for a while. I'm going to release 1.0 final and then revisit how configurable this is to cut down on the crazy number of props we support.

**Comment by carlosbensant** [comment]
@JedWatson Thanks for taking your time to reply. 

I've tried to explain my concern in a much cleaner way. Could I ask you kindly to check this issue #2152 I've opened recently.

**Comment by tiffwu** [comment]
@JedWatson This would be huge for my team as well. I'm fine with the placeholder disappearing when the user starts typing.

**Comment by jayaranigarg** [comment]
@JedWatson : Can we take this PR in? It will be of huge help!!

**Comment by Rall3n** [comment]
For a solution to keep the placeholder around (with current version) check out [this comment](https://github.com/JedWatson/react-select/issues/2152#issuecomment-470889515).

**Pull request closed without merging**
