### PR TITLE
add autoComplete as prop to the Select component

### PR DESCRIPTION
**Pull request by lvl99**
As mentioned  in issue https://github.com/JedWatson/react-select/issues/3500 and  https://github.com/JedWatson/react-select/pull/2395 and having my own need to set an explicit `autoComplete` value (namely to prevent Google Chrome from showing its autofill drop-down on top of the `react-select` drop-down) I've attempted a quick simple fix.

### CODE REVIEW

**Comment by Shperung** [comment]
In which version of the library are these changes?

**Comment by lvl99** [comment]
@Shperung whatever was on `master`?

**Comment by lvl99** [comment]
@JedWatson any view whether this is in the right direction, or acceptable or not as is?

**Comment by lvl99** [comment]
Bump

**Comment by bladey** [comment]
Resolved conflicts and created new PR #4105, closing.

**Pull request closed without merging**
