### PR TITLE
Fix #139

### LINKED ISSUE #139: No default.css in dist directory
In `0.4.7` there is no `default.css` in the `dist` directory. Is it intentional?

Thanks :-)

### PR DESCRIPTION
**Pull request by flovilmart**
- Removes default.css
- Adds react-select.css

because it makes more sense in streamlined build environments

### CODE REVIEW

**Comment by dcousens** [comment]
@flovilmart please rebase.

Looks good to me otherwise.

**Comment by flovilmart** [comment]
Rebase on?

**Comment by flovilmart** [comment]
I also removed the committed dist files as requested in the Contributors.md. Why is that?

**Comment by dcousens** [comment]
@flovilmart its irrelevant to your changes,  those dist files are created on release AFAIK.

**Comment by dcousens** [comment]
On further review, #139 has already been fixed, and this would simply make the file naming conform to a more streamline standard?  Could you elaborate @flovilmart?

This is also considered a breaking change as the file paths are different.

**Comment by flovilmart** [comment]
default.css is a pretty bad name IMHO, that's it ;)

**Comment by dcousens** [comment]
@JedWatson I leave this up to you.

**Comment by agirton** [comment]
Closing as this is no longer applicable.

**Comment by flovilmart** [comment]
Eheh no problem!

**Pull request closed without merging**
