### PR TITLE
Fix tests 1.0

### PR DESCRIPTION
**Pull request by bruderstein**
This is where I am up to. Please don't merge this yet, this is just to keep public where I'm up to. Should hopefully finish this weekend.

### CODE REVIEW

**Comment by bruderstein** [comment]
This will be the fix for #571

**Comment by bruderstein** [comment]
@JedWatson This is ready to go now - together with #609 from @MrLeebo, we're back to green \o/  - Thank you @MrLeebo for the PR!

I think there's only two bug fixes - 9767a8d and 4d5eaf5

The rest, as usual, I've tried to keep each change or fix in a separate commit, so it's possible to see why each change was made. Hope that's ok.

I'll open a new issue for the async tests, as I'd like to do those separately. At least we're back to green, and can work from there. There's probably one or two other bits that need tests now (`simpleValue={true}`, for example), but I'll add those as I see them.

**Comment by JedWatson** [comment]
Brilliant - thank you so much @bruderstein and @MrLeebo!

I promise not to do any more major test-breaking refactoring on react-select this year :wink:

**Comment by MrLeebo** [comment]
@JedWatson @bruderstein Glad to see this done. When I made my PR I flirted with fixing the Select tests, but I quit when I realized how much work that was going to be.

Would you say this merits an NPM release?

**Comment by bruderstein** [comment]
@MrLeebo I don't think there's any pressing reason to. There are only two tiny fixes, that fix edge cases (neither of which are serious), so can easily just be lumped in with the next release.  Not sure when I'll get the async tests done, but when they're in, they may turn up some stuff, which would may make a release worth it.

**Pull request merged**
