### PR TITLE
Refactored Async.

### PR DESCRIPTION
**Pull request by bvaughn**
This PR resolves the following issues #1138, #1141, #1166, #1181, #1216, and #1220.

The following props have been removed from `Async`:
* `minimumInput`: This property belongs in user-land. It conflicts with the `autoload` property and makes for complicated edge-cases (eg load initial options when component is mounted but don't load again until input value reaches a certain length).
* `searchingText`: This property was not being used and seemed redundant with `loadingPlaceholder`.

### CODE REVIEW

**Comment by TheSharpieOne** [comment]
Would have been nice to factor in pagination, it is on the [list for v1.0.0](https://github.com/JedWatson/react-select/issues/568#issuecomment-153785740)

**Comment by bvaughn** [comment]
Ah, I didn't write the list you're referring to @TheSharpieOne. (I actually wasn't even a contributor yet at that point.) In fact this is the first time I've even seen the list.

My 2 cents would be that pagination within a drop-down component seems weird. I don't know what Jed had/has in mind WRT that feature though. Maybe he has better ideas than me. 😄

Anyway this refactor fixed 6 issues (and I'm sure there's more to come on this component). Don't be greedy. 😆 😉

**Comment by TheSharpieOne** [comment]
@bvaughn, no big deal. I'm creating a PR for it now. It wasn't too much work and didn't really require much effort thanks to this refactor you did (that and the `onMenuScrollToBottom` prop which I didn't know was already there for the `<Select>`).

**Comment by jochenberger** [comment]
Since it is now the user's responsibility to implement `minimumInput`, I think there should be an example in the docs.

**Comment by bvaughn** [comment]
`minimumInput` was just a string-length check with a short-circuit that returned an empty `options` array if the string was too short. Didn't seem necessary to add to the docs (since the bigger the docs are, the more difficult it typically is to find things). If you disagree, feel free to submit a PR with the docs addition for consideration. 😄

**Comment by jochenberger** [comment]
In fact, I do disagree. For example, the fact that you need to call the callback also if you don't want any results to be shown, is something that should be pointed out IMO, otherwise people are going to have to figure it out the hard way (like I did).

**Comment by bvaughn** [comment]
As I said, feel free to submit a PR with the docs addition for consideration. Docs PRs are the easiest to contribute _and_ the easiest to review (and so much more likely to be accepted).

**Pull request merged**
