### PR TITLE
fix null reference when using opt-groups in Creatable

### PR DESCRIPTION
**Pull request by JoshMcCullough**
See here:  
- https://github.com/JedWatson/react-select/issues/59
- https://github.com/JedWatson/react-select/issues/3056

### CODE REVIEW

**Comment by JoshMcCullough** [comment]
FYI I don't think these CI failures are due to my changes.

**Comment by razh** [comment]
@JoshMcCullough 

It's failing because of lint errors/warnings:

```js
$ eslint .

/root/project/repo/src/Creatable.js
  38:7  error  'compareOption' is assigned a value but never used  no-unused-vars

/root/project/repo/src/Select.js
  1004:1   warning  Trailing spaces not allowed                         no-trailing-spaces
  1467:13  warning  'isFocused' is already declared in the upper scope  no-shadow

✖ 3 problems (1 error, 2 warnings)
  0 errors, 1 warning potentially fixable with the `--fix` option.
```

https://circleci.com/gh/JedWatson/react-select/1881

**Comment by JoshMcCullough** [comment]
Yes I know, but check my changes -- unrelated to those files, those lint issues were already present before this PR, so should be fixed in master.

**Comment by JoshMcCullough** [comment]
Fixed one lint issue here and opened a PR for the others: https://github.com/JedWatson/react-select/pull/3343

**Comment by ebonow** [comment]
Greetings @JoshMcCullough and thank you for the submission. Also apologies for the delay in a response. The community and its contributors deserve better and I apologize that this has remained open so long without reply.

I wanted to test that this issue still exists and it appears that it has already been resolved. Here is a fork of the example posted in #3056 with the only change being an update from react-select v2.0.0 to v2.4.4

demo: [codesandbox](https://codesandbox.io/s/react-select-pr-3338-creatable-support-with-groups-je1bn)

Since this issue no longer appears to be present, I thought it appropriate to close this PR but also to thank you for offering your time and contributing code in an effort to help fellow developers experiencing this same issue. The team and the community are appreciative for any contributions to making react-select better.

If you feel that this was closed prematurely or are able to reproduce errors, please feel free to provide an example and we can revisit and reopen this PR.

**Pull request closed without merging**
