### PR TITLE
Ref #25 - Allows numbers (not just strings) as option labels and values.

### PR DESCRIPTION
**Pull request by jacobdfriedmann**
If a multi-select, passes an array to the onChange function (instead of concatenated string)
which is empty when nothing is selected.

If a single select, passes the single value to the onChange function and null if nothing
is selected.

### CODE REVIEW

**Comment by julen** [comment]
@jacobdfriedmann any chance to have this PR rebased against the current state of master? I've hit this issue and would love to see it fixed in the library.

If you cannot do it let me know and I'll be glad to take over.

**Comment by jacobdfriedmann** [comment]
@julen Done! Been meaning to do that for awhile. Feel free to make any improvements if you think I could've done anything better.

**Comment by julen** [comment]
@JedWatson any chance you could integrate this anytime soon?

**Comment by dannyshaw** [comment]
looking forward to this being merged

**Comment by JedWatson** [comment]
Sorry for the delay. There's a couple of reasons I can't merge this as-is that are hard to explain right now. I need to think through it thoroughly, and make sure I've got all the use-cases I want to meet sorted out. 

I'll make some time this weekend to review it and come back with something that works (based on this).

Thanks too for the initial work @jacobdfriedmann, really appreciate it and again sorry I've left it hanging so long.

**Comment by Jayshua** [comment]
Any updates on this? It would be very nice to not have to convert to strings all the time.

**Comment by dcousens** [comment]
@jacobdfriedmann could you please rebase?
Sorry for the inconvenience.

**Comment by dcousens** [comment]
This fixes https://github.com/JedWatson/react-select/issues/25.

**Comment by agirton** [comment]
Closing as users can enter a number and it will resolve to the word. E.g. 23 -> Twenty Three.

**Pull request closed without merging**
