### PR TITLE
Clear input value on receiving props with another value.

### PR DESCRIPTION
**Pull request by yuri-sakharov**
Hi,
Should be fixed this bug https://github.com/JedWatson/react-select/issues/2155.
Thanks.

### CODE REVIEW

**Comment by JedWatson** [comment]
Solid fix @yuri-sakharov, thanks!

**Comment by yuri-sakharov** [comment]
@JedWatson thank you too.

**Comment by jharris4** [comment]
FYI this was a breaking change for me (and took me a little while to track down after upgrading!)

My value prop (actually a list of values since I'm in multi mode) are coming from an immutable collection which I was converting to an array of values in a render function.

I had to refactor things to instead do the conversion in componentWillReceiveProps (only if the immutable collection changed) and assign to state for use in the render function.

I can see the value of this PR, but it might be helpful to draw attention to it in the docs or something in case other people get tripped up by this as well.

**Comment by yuri-sakharov** [comment]
Hi, @jharris4 
Thank you for comment I fixed it in https://github.com/JedWatson/react-select/pull/2299

**Comment by hiredgun** [comment]
@yuri-sakharov was this fix merged?

**Comment by yuri-sakharov** [comment]
@hiredgun I don't know and don't have rights for merge. The question should be addressed to collaborators.

**Pull request merged**
