### PR TITLE
add the ability to display multiselect options externally

### PR DESCRIPTION
**Pull request by uxtx**
Thanks so much for this fantastic library - we're using it quite extensively in some internal components at the company i work for. One request we've received repeatedly as we've been working with multiselect dropdowns is the ability to optionally show large list of options externally, similar to this jquery plugin: http://www.jqueryscript.net/demo/Simple-Mobile-Friendly-jQuery-Tags-Input-Plugin-Taxonomy/

I've attached a screenshot of the option below.

screen shot 2017-10-24 at 5 49 02 pm

### CODE REVIEW

**Comment by uxtx** [comment]
resolved conflicts

**Comment by cristianfraser** [comment]
Why is this uncertain? Will it get released with 1.0?

**Comment by uxtx** [comment]
i'm definitely open to feedback on this ticket - I know my team is eager to get this in - we've got some lists of multi-select options ranging around 800+ items, and having the option to render these outside of the select controller would definitely be welcome.

**Comment by uxtx** [comment]
@gwyneplaine @JedWatson any way I could get a review?

**Comment by bowers-bv** [comment]
Just adding my voice… this feature is really needed.

**Comment by jennifergarcia** [comment]
Would love to see this contribution launched.  Any ideas when it would go out?

**Comment by luberg** [comment]
+1

**Comment by nod** [comment]
+1

**Comment by jarrodb** [comment]
+1 merge please!

**Comment by ryanberger** [comment]
+1, please merge!

**Comment by andrewskaggs** [comment]
Another +1 for merging this feature. This is the exact customization work I needed to do to use the control.

**Comment by uxtx** [comment]
updated.

**Comment by GuillaumeRenouvin** [comment]
+1

**Comment by LaureRC** [comment]
+1

**Comment by jarrodb** [comment]
What is the issue with merging this request?  There is plenty of community support, it is line with the project goals, and is a great added feature.

**Comment by AmauryLiet** [comment]
Hi @gwyneplaine @JedWatson, we would love to have your feedback on this! :)

**Comment by oscarlnetoo** [comment]
@uxtx, any news about this feature?

**Comment by Rall3n** [comment]
@oscarlnetoo As this was resolved by the release of version 2, this might not be merged as this was for version 1.

Following is a solution using `react-select`s own [component framework](https://react-select.com/components) for customizing the inner parts of the select: [CodeSandbox](https://codesandbox.io/s/2p0nj6495n)

@gwyneplaine this merge request should be closed due to it being for version 1

**Comment by uxtx** [comment]
Makes sense to me - if there's any interest in trying to port this functionality into v1 - I can resolve the conflicts and add it there - but seeing as how this is available in v2 - it may not be worth it. Let me know if there's a groundswell of interest - but it sounds like this can be closed otherwise.

**Pull request closed without merging**
