### PR TITLE
add aria-required attribute to select

### PR DESCRIPTION
**Pull request by imanpalsingh**
## Description
if `aria-required` is passed to the select component, it is not drilled to the input element. This update adds it to the props of `Select` component

This 
```
<Select
    options={options}
    aria-required={true}
  />
```

will result in 

```
<input aria-required="true  ... />
```

For issue : #5006

### CODE REVIEW

**Comment by adamrparsons** [comment]
hello @Methuselah96 I was wondering if its possible to see this pr reviewed? It would be very helpful for our screen reader users

**Review by StorytellerCZ — APPROVED** [review]

**Review by kethomas — APPROVED** [review]

**Comment by SimonSelg** [comment]
@imanpalsingh thanks for the PR! are there any updates on getting this merged?

**Comment by Methuselah96** [comment]
@Rall3n Any objections?

**Comment by Rall3n** [comment]
@Methuselah96 I added `aria-required` as part of the [`required` PR](https://github.com/JedWatson/react-select/pull/4882).

Would need some editing if we merged both, but I think the ability to set `aria-required` separately should be added.

**Comment by imanpalsingh** [comment]
> Would need some editing if we merged both

@SimonSelg @Methuselah96 @Rall3n 
I have resolved the merge conflicts.

Let me know if you meant something else

**Comment by imanpalsingh** [comment]
Looks like after https://github.com/JedWatson/react-select/pull/4882 this won't be required. This PR almost turned a year old, adios

**Pull request closed without merging**
