### PR TITLE
Search ignoring character variations

### PR DESCRIPTION
**Pull request by pedroseac**
This change is [Reviewable](https://reviewable.io/reviews/jedwatson/react-select/359)

### CODE REVIEW

**Comment by bruderstein** [comment]
I'm half torn between giving this the :+1: , and saying that if you want to do this, you should be using your own custom `filterOptions` function.  I can see this would be something that would grow significantly (e.g. would be good to have umlauts in there, speaking from Germany :smile:).  I'd also make this optional, so add a prop to turn this on or off (e.g. ignoreAccentsInFilter={true}).  

Note you don't need the `|` in a group, and you can chain the replacements, so this works fine
```js
string = string.replace(/[áàâã]/gi, "a")
    .replace(/[éèê]/gi, "e")
    .replace(/[íìî]/gi, "i")
// etc
```

There is a suggestion from @brianreavis in #227 to use [sifter.js](https://www.npmjs.com/package/sifter) for the filtering, which would solve this sort of thing nicely.

**Comment by pedroseac** [comment]
sorry for the insanely delayed respose!

thanks for the comment and corrections @bruderstein! I gonna have a better look at it. 

My thinking at the time was: "Google does like this, why not you?". Huahaha!

**Comment by pedroseac** [comment]
https://github.com/JedWatson/react-select/blob/master/lib/utils/stripDiacritics.js =)

**Comment by Lenne231** [comment]
Is there any progress on this? I would really like to use umlauts as well...

**Comment by agirton** [comment]
This has been resolved by using `ignoreAccents` prop and setting it to false.

**Pull request closed without merging**
