### PR TITLE
creatable-runs-onInputChange-prop: Fix Creatable to use onInputChange…

### PR DESCRIPTION
**Pull request by wmcmeans**
… function passed as prop

### CODE REVIEW

**Comment by wmcmeans** [comment]
Addresses issue #1349

**Comment by theopak** [comment]
Looks like an onInputChange prop works for Creatable in v0.9.1 but not v1.0.0-rc.1. This branch fixes the issue for me. Thanks! 

Hey @JedWatson is there any way this PR can be merged soon?

**Comment by TkDodo** [comment]
👍  can you please accept this PR .. ?

**Comment by skmvasu** [comment]
@JedWatson Is it possible to merge this branch soon? This fixes some blocking issues for us. Thanks :)

**Comment by takashi** [comment]
I think this change had been already implemented in ver. 1.0.0-rc2

**Comment by theopak** [comment]
@takashi Good find! I do see that a (slightly different) fix was added to the base branch after this PR was opened, and that was released with v1.0.0-rc.2 which works for me.

- You can see that it exists here: https://github.com/JedWatson/react-select/blob/master/src/Creatable.js#L169 (blame https://github.com/JedWatson/react-select/commit/a91f539c74da674c4be66ff856c085e8ce8d09d7)
- The base branch does not have the test from this PR (and IMO the test is valuable): https://github.com/JedWatson/react-select/blob/master/test/Creatable-test.js

**Comment by JedWatson** [comment]
I believe this can be closed now because #2057 has been merged, could everyone please confirm that it solves the problem correctly for their use-case? and continue discussion on #2056 if not.

Thanks!

**Pull request closed without merging**
