### PR TITLE
Remove `jsnext:main` entry

### PR DESCRIPTION
**Pull request by jochenberger**
The file does not exist, this sneaked in in https://github.com/JedWatson/react-select/pull/1953/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R6

### CODE REVIEW

**Comment by jochenberger** [comment]
cc @gwyneplaine

**Comment by gwyneplaine** [comment]
yes that definitely shouldn't be there, thanks for that @jochenberger
lgtm

**Comment by jochenberger** [comment]
See also #1981

**Comment by JedWatson** [comment]
I've fixed it the other way, by adding the es build.

**Pull request closed without merging**
