### PR TITLE
focusDefaultOption prop

### PR DESCRIPTION
**Pull request by Francismb**
### focusDefaultOption prop

This prop enables or disables the automatically applied focus to the first or last option in the drop down menu of options.

The use case I found is that if you want a free text search select input but to also have auto completing options, much like a google search box.

https://github.com/JedWatson/react-select/issues/2848
https://github.com/JedWatson/react-select/pull/3324
https://github.com/JedWatson/react-select/pull/3484

### CODE REVIEW

**Comment by dko-slapdash** [comment]
Until this is merged, is there some work-around to achieve the same behavior? Like not focusing a menu item at all when the menu is opened due to a text match (except when an arrow-down is pressed).

**Comment by frazboyz** [comment]
Not that I have found @dko-slapdash

**Comment by ShonP** [comment]
@frazboyz thanks for this pr. please anyone merge when possible

**Comment by JedWatson** [comment]
Thanks for this @frazboyz, I'd be happy to merge this but could you please add an example demonstrating usage that we can use to test and demo how it works? (the "advanced" page probably the right place to do this)

**Comment by frazboyz** [comment]
All yours @JedWatson Example added to the advanced section.

**Comment by dannnylin** [comment]
@JedWatson  can we please merge?

**Comment by marcolazzarini** [comment]
Is the version containing this fix already released?

**Comment by dannnylin** [comment]
@JedWatson @gwyneplaine

**Comment by marcolazzarini** [comment]
Let me say that this feature is **fundamental** in order to use react-select as base for an action menu, like:

Screenshot 2019-12-05 at 08 41 03

in this kind of situation, is weird (and basically wrong) to have any of the options automatically focused opening the menu

**Comment by frazboyz** [comment]
@mitchellhamilton Any chance you can take a final look?

**Comment by eugenet8k** [comment]
Please submit, this is a helpful compromise for another use case. If `isMulti={true}` and `closeMenuOnSelect={false}` I want users to be able to select multiple options one by one. At this moment, each time users select an option it disappears from `options` hence `getNextFocusedOption` mandatory will focus first or last one. 

Having `focusDefaultOption={false}` would at least fix the UX for mouse users, as a nearby to the previously selected option will be focused due to mouse hover event. For keyboard users, it won't help though...

**Comment by diegosps** [comment]
@flexdinesh pinging you because I saw the pinned issue.

You can see from the linked issue and pr, this has been requested multiple times and it is a longin waiting bug fix.

**Comment by bladey** [comment]
Thanks for your contribution @Francismb!

This PR has now been brought up to date and tweaked so it can be merged - see PR #4080 for more details.

Closing this PR in favor of #4080.

**Comment by raulhinojosa** [comment]
Anybody found a workaround at least?

**Pull request closed without merging**
