### PR TITLE
Fix for Menu bottom is scrolled into view even when menuShouldScrollIntoView=false

### LINKED ISSUE #3459: Scroll into view issue even when menuShouldScrollIntoView=false
When the menu is placed inside a scrollable div a bit down on the page the menu always triggers a scroll to bottom of this div even when menuShouldScrollIntoView=false. This is really a big issue as it scrolls the parent container so much so the react select input does not become visible.

There is a simple fix for this issue in PR #3262

### LINKED ISSUE #4060: menuIsOpen causing page to scroll down
When setting menuIsOpen={true} the page getting scrolled down

### PR DESCRIPTION
**Pull request by torkelo**
When the menu is placed inside a scrollable div a bit down on the page the menu always triggers a scroll to bottom of this div even when menuShouldScrollIntoView=false. This is really a big issue as it scrolls the parent container so much so the react select input does not become visible. 

Was fixed by adding the if (shouldScroll) to the last case in getMenuPlacement.  This case did not check this bool flag, the other scenarios in this case switch do check this variable. 

Fixes #3459

### CODE REVIEW

**Comment by torkelo** [comment]
rebased with master and created a bug report issue #3459

**Comment by torkelo** [comment]
Any change to merge this bugfix?

**Comment by freewind** [comment]
Why is this PR can't be merged? Have been waiting for many days!

**Comment by wangjohn** [comment]
I've also had a large number of users experiencing this issue, and it's a really huge UX issue since it's unexpected for the container to be moving around. It would be very nice to get this merged!

**Comment by MichaelKostin** [comment]
The same. I'm waiting for this changes.

**Comment by MichaelKostin** [comment]
@gwyneplaine could you take a look on the PR?

**Comment by freewind** [comment]
Please!

**Comment by freewind** [comment]
Almost a year !!!

**Comment by freewind** [comment]
@JedWatson @gwyneplaine Please have a look at this PR, thanks

**Comment by torkelo** [comment]
Rebased this against latest master

**Comment by torkelo** [comment]
Please try to find time to merge this, simple fix to a bug that forces us to maintain an npm fork.

**Comment by torkelo** [comment]
I know it's hard to fine time to review PRs but this seems like an easy one to review

**Comment by torkelo** [comment]
If anyone needs this fix: https://www.npmjs.com/package/@torkelo/react-select

**Comment by dprokop** [comment]
@JedWatson friendly ping :)

**Comment by bladey** [comment]
Hey @torkelo, could you please provide a CodeSandbox of this PR with a working example? I'd like to test and get this merged.

**Comment by torkelo** [comment]
Not sure I will have time this week. You mean a CodeSandbox that replicates the issue or one that includes this change?

**Comment by torkelo** [comment]
You can try this change on https://play.grafana.org/d/000000012/grafana-play-home?editPanel=2&orgId=1 
Most dropdown's are react-select fork with this PR applied:

Screenshot from 2020-06-08 09-28-59

**Comment by bladey** [comment]
Thanks @torkelo!

**Comment by bladey** [comment]
@JedWatson looks good to me, for your review.

react-select - https://codesandbox.io/s/react-select-v3-sandbox-mzjmv?file=/example.js
@torkelo/react-select - https://codesandbox.io/s/react-select-v3-sandbox-yi6sv?file=/example.js

**Review by bladey — APPROVED** [review]

**Comment by torkelo** [comment]
yay! can remove my npm fork after this :)

**Comment by brentg5** [comment]
@JedWatson Looks like this is super close to being merged! I'd love to have this fix ❤️

**Comment by Methuselah96** [comment]
I've started [a fork](https://github.com/react-select-oss/react-select) of react-select. Feel free to resubmit this PR on the fork and we can get it merged and released.

**Comment by brookeangel** [comment]
Echoing everyone who has advocated for this fix being merged 😄  This would be super helpful.

**Review by qxFisher — APPROVED** [review]

**Comment by 7ruth** [comment]
Echoing everyone who has advocated for this fix being merged 😄 This would be super helpful.

**Comment by 7ruth** [comment]
Really looking forward to this merge, thank you for awesome lib! 🙏

**Comment by ebonow** [comment]
Sorry everyone for the long wait. This seems like an obvious bug fix and will move this into consideration for next version release.

**Review by ebonow — APPROVED** [review]

**Comment by ebonow** [comment]
@freewind (or anyone else) have any reservations about this?

**Comment by freewind** [comment]
@ebonow Sorry, just have been waiting too long and feel very sad

**Comment by ebonow** [comment]
> @ebonow Sorry, just have been waiting too long and feel very sad

@freewind I can understand that and I empathize. I feel bad that so many people have given their time to contribute and then didn't even get the courtesy of a response. It's exactly why myself and others are putting in so much of our own free time to work through everything, and we're doing our best to make it right. 

And while just last year there were 1,452 issues closed, 151 PR's closed, 56 PR's merged, communication could have been much better, so it's something that's been made a priority. As such, please feel free to use the discussion area or subscribe to https://github.com/JedWatson/react-select/issues/4293 for updates on releases if that's something that interests you.

That all said, I am committed to working through every issue and PR and any help with that is welcome.

**Review by JedWatson — APPROVED** [review]

**Comment by JedWatson** [comment]
Hi everyone, we finally got to this PR in our review this week, and it has now been approved and will be released imminently.

I want to say I'm sorry for leaving this so long. It's heartbreaking, and I apologise. It's such a simple fix to a clear bug that unfortunately just got lost in the noise for me.

@ebonow @Methuselah96 @Rall3n and @bladey have my immense gratitude for helping get the project back under control from a maintenance perspective. As Eric said, it's been an epic undertaking 🙏

**Comment by TeqTamLe** [comment]
this issue is not resolve :(

**Pull request merged**
