### PR TITLE
convert Select to ES6 class

### PR DESCRIPTION
**Pull request by jochenberger**

### CODE REVIEW

**Comment by jochenberger** [comment]
Not sure what's going wrong here. I can't get the dev environment to run so I can't really do much debugging. I guess there's a function bind missing.

**Comment by jochenberger** [comment]
The test passes on my machine. :-/

**Comment by agirton** [comment]
Hi @jochenberger how did you convert these to ES6 classes, did use the React codemod or by hand?

**Comment by jochenberger** [comment]
By hand

**Comment by agirton** [comment]
Also what was the primary reason for creating a PR for each component?

**Comment by jochenberger** [comment]
To have smaller chunks for you to review and merge

**Comment by agirton** [comment]
I see your point. Thank you. Can you try closing and reopening PR to see if that fixes the CI build?

**Comment by jochenberger** [comment]
Huh? Interesting...

**Pull request merged**
