### PR TITLE
fix label for multiselect

### PR DESCRIPTION
**Pull request by SVITY**
In Firefox labels with several words are shown into 2 lines instead 1 line http://take.ms/J3hs7
I added white-space into multi.scss and ran build. 
If you want I can create pull request without build.

### CODE REVIEW

**Comment by protron** [comment]
Isn't this already fixed in master by #1300 ?

**Comment by SVITY** [comment]
@protron Yes, it fixed.  Probably I use not the last version of react-select, without this fix.
Just I wanted to contribute to the great react component.

Thanks

**Comment by SVITY** [comment]
https://github.com/JedWatson/react-select/pull/1300 it fixed the bug. But the last master commit does not have these changes. How is it possible? 
Less directory has changes, but nothing into dist directory.

**Comment by gwyneplaine** [comment]
@SVITY you need to run the build script `npm run build` to compile the changes in the less file to dist

Issue closed, as bug fixed in #1300 (merged into master)

**Pull request closed without merging**
