### PR TITLE
[v2] Fix for #2716 - Missing type annotation for U.

### PR DESCRIPTION
**Pull request by himerus**
Fix for #2716 thanks to @erkan1991 ([fix](https://github.com/JedWatson/react-select/issues/2716#issuecomment-398260603)).

screenshot of atom 6-20-18 9-45-54 am

### CODE REVIEW

**Comment by himerus** [comment]
Darn, the commit message has the wrong issue number. Let me know (ping) if I should resubmit.

**Comment by gwyneplaine** [comment]
@himerus  thanks for this, looks good to me, if you could update the commit with the correct issue number, i'll merge it in 👍

**Comment by himerus** [comment]
@gwyneplaine Should be GTG now. Thanks!

**Comment by gwyneplaine** [comment]
merged, thanks @himerus

**Comment by erkan1991** [comment]
Hey @gwyneplaine, is there a ETA for the next release that includes this fix ?

**Pull request merged**
