### PR TITLE
Allow the formatGroupLabel be dependent to inputValue

### PR DESCRIPTION
**Pull request by montaseri**
The `formatGroupLabel` should have the same feature like `formatOptionLabel`.

### CODE REVIEW

**Comment by Rall3n** [comment]
> The `formatGroupLabel` should have the same feature like `formatOptionLabel`.

@montaseri Could you elaborate on why it **should** have the same features (in regards to `inputValue`)?

**Comment by ebonow** [comment]
>  Could you elaborate on why it **should** have the same features (in regards to `inputValue`)?

One possible use-case is if you want to filter groups by input or apply syntax highlighting to the group labels depending on the input.

I believe there may be a larger discussion perhaps to be had about accessibility and whether group labels should be focusable and creating a built-in to access the group heading as a string such as `getGoupLabel`...

**Comment by JedWatson** [comment]
I'm generally 👍 to this change, but it would be good to link to an issue that describes the reasoning behind the change. I can think of some but not sure if they're actually valid real-world things.

Other than that, this needs to pass CI / have a changeset / be up to date with master... @montaseri there's an option to let people with write access to the target repo update the PR, if you tick that we can help you out

**Comment by montaseri** [comment]
I would like to close the PR for now.

**Pull request closed without merging**
