### PR TITLE
Fixed #284. Added support for direction control.

### LINKED ISSUE #284: Control opening direction up/down
Hi! 
Is there a way to control the opening direction programmatically?
kinda like the native select tag behavior, opens up or down (when there is not enough space for the dropdown to open up ).
thanks!

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes #284 . This adds support for select direction of menu

### CODE REVIEW

**Comment by rvignacio** [comment]
Any chance we get this merged?

**Comment by JedWatson** [comment]
Thanks for the PR @Kingwl and sorry it's taken so long to review.

Makes sense as a prop, but I'm wondering if/how this should interact with auto-detecting space around the control instead if we were to implement that?

What are your thoughts?

**Comment by adjohnson916** [comment]
@JedWatson It'd be great if this feature made it into a release soon.

**Comment by burtyish** [comment]
> Makes sense as a prop, but I'm wondering if/how this should interact with auto-detecting space around the control instead if we were to implement that?

@JedWatson FYI, #810 mentions a solution which provides automatically determining the direction based on available space via usage of `tether.js`.

**Pull request closed without merging**
