### PR TITLE
Remove browser alias fields

### PR DESCRIPTION
**Pull request by Methuselah96**
Resolves https://github.com/JedWatson/react-select/issues/3802.

The `browser` alias outputs aren't doing much anyway besides causing the bug in SSR (they just remove the `typeof window !== undefined` check in one place), so I think it practically makes sense to remove them even though we're technically doing everything correctly.

### CODE REVIEW

**Comment by Methuselah96** [comment]
Need to look into this some more.

**Comment by JedWatson** [comment]
@mitchellhamilton do you know anything about this that would make this PR not the best way forward?

**Comment by mitchellhamilton** [comment]
There's nothing really wrong with merging this PR since in this case, the browser builds are pointless. react-select depends on emotion though and emotion has browser builds which have a non-trivial bundle size saving so this change won't really solve the problem for people.

**Comment by Methuselah96** [comment]
True. I've added a [concluding comment](https://github.com/JedWatson/react-select/issues/3802#issuecomment-776333493) to the linked issue.

@JedWatson Up to you whether this is worth merging. The benefit of merging it would be that it would then definitely not be our problem and we could tell people to bug Emotion, their SSR library, and/or Webpack instead of bugging us. The browser builds (as Mitchell pointed) are currently pointless.

**Review by JedWatson — APPROVED** [review]

**Pull request merged**
