### PR TITLE
Feature request - props.ignorePunctuation

### PR DESCRIPTION
**Pull request by wi-ski**
This is an attempt to remedy some weird behavior I was getting from a previous PR.

Ultimately, I'd like an option for ignoring punctuation in the options list.

### CODE REVIEW

**Comment by willdembinski** [comment]
Alas - I'm still confused as to why CI is failing.

Node version: v4.7.3
cover && coverall run to completion locally.

**Comment by willdembinski** [comment]
This PR has:

a. A new prop: `ignorePunctuation` that allows for: Ignoring punctuation represented in the following regex: `/[.,\/'#!%\^?&\*;:{}=\-_`~()]/g` when assigned as a boolean.  Additionally can take a custom regex.
b. Pretty decent test coverage
c. Updated readme.

Would literally *LOVE* some guidance on why CI hates me.  It passes all of the tests locally in flying green colors.

But travis CI be like: http://www.vitamin-ha.com/wp-content/uploads/2012/05/VH-35bcoq.jpg
And I be like: https://imgflip.com/s/meme/Jackie-Chan-WTF.jpg

Anyways - would love some input.

**Comment by willdembinski** [comment]
Would literally *LOVE* some guidance on why CI hates me.  It passes all of the tests locally with flying green colors.

But travis CI be like: http://www.vitamin-ha.com/wp-content/uploads/2012/05/VH-35bcoq.jpg
And I be like: https://imgflip.com/s/meme/Jackie-Chan-WTF.jpg

Anyways - would love some input.

**Comment by bassjacob** [comment]
@willdembinski not to worry, I think this is due to https://github.com/tmpvar/jsdom/issues/1728

we might have to lock the version of jsdom during testing to < 9.10 until that is resolved. Yours is the only pull request since jsdom@9.10 was released a couple of days ago.

@JedWatson should we manually pin jsdom at a lower version here?

**Comment by willdembinski** [comment]
@bassjacob - Thanks for the heads up.  As for the PR - is there anything else I can do for this type of feature?  I don't want to assume it's **needed** but  it makes me feel good :stuck_out_tongue_closed_eyes:

**Comment by jossmac** [comment]
We intend to address this in v2

**Pull request closed without merging**
