### PR TITLE
Adds onAdd handler

### PR DESCRIPTION
**Pull request by flovilmart**
As per discussion on #151

### CODE REVIEW

**Comment by dcousens** [comment]
Looks good to me.

Thanks @flovilmart

**Comment by dcousens** [comment]
Actually, can you change `allowCreate` to `canAdd`?

**Comment by flovilmart** [comment]
Yep. I'll do that. BTW The onAdd fires with the same parameters as onChange.

**Comment by dcousens** [comment]
@flovilmart excellent :)

**Comment by dcousens** [comment]
bump @flovilmart

**Comment by flovilmart** [comment]
Bump?

**Comment by dcousens** [comment]
> Actually, can you change allowCreate to canAdd?

**Comment by dcousens** [comment]
> Actually, can you change allowCreate to canAdd?

See https://github.com/flovilmart/react-select/pull/2

**Comment by dcousens** [comment]
@flovilmart anything holding this back?

**Comment by brianreavis** [comment]
As mentioned in #235, an `onAdd` event should should be paired with an `onRemove`, right? Or is this more of an `onCreate` event? Sorry, I'm a little confused on the terminology here. With the "multi" mode, an `onAdd` event that really represents when new items are created is going to create confusion.

**Comment by flovilmart** [comment]
I agree that onCreate would be more appropriate

**Comment by brianreavis** [comment]
@dcousens Your thoughts? @flovilmart Sorry for suggesting we go back and forth on this!

**Comment by flovilmart** [comment]
No problem. That's a quick fix and it's already on production with my fork :) better do it now!

**Comment by dcousens** [comment]
@brianreavis excellent point,  `onCreate` and `onRemove` sound fine.

I'll close my PR, @flovilmart are you happy to fix this soon? If not, I'll merge and manually fix. :+1: 

Thanks for this.

**Comment by flovilmart** [comment]
Il do it tomorrow.also, the flag should be back to canCreate :)

**Comment by dcousens** [comment]
Bump @flovilmart,

**Comment by seanmheff** [comment]
Bump

**Comment by agirton** [comment]
Closing as this is no longer applicable.

**Pull request closed without merging**
