### PR TITLE
Cleaned up custom :menuRenderer example to use react-virtualized-select HOC

### PR DESCRIPTION
**Pull request by bvaughn**
A live version of this PR can be seen here: http://bvaughn.github.io/react-select/

With PR #859 merged and v1.0.0-beta12 released, I released a new HOC- [`react-virtualized-select`](https://github.com/bvaughn/react-virtualized-select/)- so that I can take on the ownership of maintaining an interface between react-select and react-virtualized. A demo of the HOC can be seen here: http://bvaughn.github.io/react-virtualized-select/

This PR updates the example to use that HOC. (I think it's the simplest way to integrate the 2 libraries so it seems like the way we should show in a demo.)

### CODE REVIEW

**Comment by omgaz** [comment]
LGTM, just update to the project contrib coding conventions specifically spacing. https://github.com/keystonejs/keystone/wiki/Coding-Standards

**Comment by bvaughn** [comment]
Hi @omgaz. I'm not sure I understand. Are you suggesting I change from tabs to spaces? I attempted to follow the default used in the other files.

**Comment by omgaz** [comment]
Hey, sorry my bad mis-read the contrib. Statement retracted! LGTM :fish_cake:

**Comment by JedWatson** [comment]
Thanks @bvaughn! looks great.

**Pull request merged**
