### PR TITLE
fix Select close when scroll on menu in IE11

### PR DESCRIPTION
**Pull request by rakid**
related to #1020 and #2816

### CODE REVIEW

**Comment by DaveCole** [comment]
This fixes the issue but it would be nice if clicking outside of the element closed the drop-down.  Hopefully @JedWatson sees this soon.

**Comment by rakid** [comment]
Hey @DaveCole! did you test it on differents browsers, especially IE11? 
the url of fiw is : https://deploy-preview-3013--react-select.netlify.com/home

**Comment by DaveCole** [comment]
Thanks @rakid - I did test it on IE11, as well as Chrome; the fix works very well; there's just one case where it didn't quite work for me, and that was if I opened the select, scrolled a little bit, then went to click outside of the expanded window -specifically- to the right of the select.  If I clicked anywhere above or below it, it would close.  I'm wondering if maybe there's a cropped div catching the event or something in that case.  Anyhow the fix makes things way, way better.  Thanks again.

**Comment by rakid** [comment]
Ok I just figure out the bug you have, I will try to fix it.
Maybe I need to add this code
`inputRef.focus()` before return?

**Comment by piotrwitek** [comment]
Hey @JedWatson @gwyneplaine are you willing to merge this PR? Thanks!

**Comment by sunil4444** [comment]
Waiting for this fix

**Comment by chris-herring** [comment]
Also need this fix.

**Comment by sbaergen** [comment]
@JedWatson @gwyneplaine Any possibility of this being merged soon?

**Comment by gwyneplaine** [comment]
thanks for this @rakid, merged

**Pull request merged**
