### PR TITLE
WIP: Select should open when clicked

### PR DESCRIPTION
**Pull request by jochenberger**
fix for #1980

### CODE REVIEW

**Comment by jochenberger** [comment]
actually, I can only get the test to run if I revert 3f102e51079d59af862923bb01d10181b50b2b34

**Comment by jochenberger** [comment]
I can't figure out why the test fails. It gets to https://github.com/JedWatson/react-select/blob/v1.0.0-rc.8/src/Select.js#L264 and to https://github.com/JedWatson/react-select/blob/v1.0.0-rc.8/src/Select.js#L181, but not to https://github.com/JedWatson/react-select/blob/v1.0.0-rc.8/src/Select.js#L315.

**Comment by ls-guillaume-lambert** [comment]
This is a regression in the latest RC releases?

**Comment by jochenberger** [comment]
I suspect that jsdom does not fire the focus events that should trigger `handleInputFocus`. Upgrading it does not seem to help.

**Comment by jochenberger** [comment]
cc @JedWatson

**Comment by JedWatson** [comment]
@bruderstein any chance you can help shed some light on this? see #1980 for context

**Comment by JedWatson** [comment]
OK I worked through this separately and committed a fix.

It was important to manage the `initialFocus` option for `createControl`, and explicitly call `findAndFocusInputControl` at the right time to correctly simulate user interaction.

Thanks for pointing me in the right direction @jochenberger

**Pull request closed without merging**
