### PR TITLE
fixed selected option width issue

### PR DESCRIPTION
**Pull request by shreekeshmurkar**
Fixed following issue of width for selected option
https://github.com/JedWatson/react-select/issues/5251

Before fix:
image

After fix:
image

### CODE REVIEW

**Comment by shreekeshmurkar** [comment]
@lukebennett88 Please review

**Comment by lukebennett88** [comment]
Thanks for your PR @shreekeshmurkar. 
Unfortunately this method no longer causes the element to be animated.

**Review by lukebennett88 — CHANGES_REQUESTED** [review]
Thanks for your PR @shreekeshmurkar.
Unfortunately this method no longer causes the element to be animated, so we will have to think of another way to fix this issue.

**Comment by lukebennett88** [comment]
I've taken a shot at fixing this bug in another PR
https://github.com/JedWatson/react-select/pull/5376

**Comment by lukebennett88** [comment]
This has been fixed in [`react-select@5.5.2`](https://github.com/JedWatson/react-select/releases/tag/react-select%405.5.2).
Closing as a duplicate.

**Pull request closed without merging**
