### PR TITLE
proposed fix #211 - close dropdown when clicking on select

### LINKED ISSUE #211: Close dropdown when clicking on select
right now the dropdown only closes when clicking somewhere outside of the select-control.
so: the user opens the dropdown by clicking on the select element, but has to move the mouse outside the element in order to close it (if he doesn't want to select any of the options)

it would be nice to add functionality so the dropdown opens when clicking on the select-control, and closes when clicking on it while the dropdown is open

### PR DESCRIPTION
**Pull request by MaaikeB**

### CODE REVIEW

**Comment by nickbouton** [comment]
+1, would love to see this merged in.

**Comment by anton-kabysh** [comment]
+1, expect the same functionality.

**Comment by borisd** [comment]
+1, please merge, this is how select should work

**Comment by JedWatson** [comment]
I'm on board. Merging.

**Comment by JedWatson** [comment]
This has broken several tests, sorry @bruderstein!

```
Select with multi=true and searchable=false selects multiple options
Select with multi=true and searchable=false calls onChange when each option is selected
Select with multi=true and searchable=false removes the selected options from the menu
```

Not sure at a quick glance between the PR and the tests why these now fail, I'll have to look into it more closely. Will come back to it soon.

**Comment by bruderstein** [comment]
I'll take a look. If it's an easy/obvious fix, am I OK to simply commit it?

**Comment by JedWatson** [comment]
Thanks - direct commit is fine, do tag this issue so we can see what you changed though, I'd love to know what the fix is :)

**Comment by bruderstein** [comment]
Guessing because the tests assume the menu is still open after the first
selection. Should be trivial to fix (just need to open the menu after each
selection)

**Comment by bruderstein** [comment]
....aaaaaand we're green :smile:

**Pull request merged**
