### PR TITLE
feat(select): add maxOptions prop

### PR DESCRIPTION
**Pull request by JalilArfaoui**
Attempt to implement #3091

### CODE REVIEW

**Comment by The-Code-Monkey** [comment]
Can this go ahead please as it would make it much easier

**Comment by GMchris** [comment]
This is quite important, as I currently show hundreds of results, and have resorted to only showing results after 3 letters.

**Comment by diogocorrea** [comment]
It would be really helpful to have this feature implemented 👍

**Comment by elocin11** [comment]
This is great.

**Comment by bladey** [comment]
Hey @JalilArfaoui,

Thanks for your contribution to `react-select`.

I'd like to get this reviewed and merged in, however the tests are currently failing, if possible - could you please rebase this so it's up to date with master?

Thank you!

**Comment by bladey** [comment]
Hey @JalilArfaoui, let me know if you've moved on from this and we'll re-assess the PR to get it merged. Thank you!

**Comment by bladey** [comment]
Resolved conflicts and created new PR #4111.

**Comment by JalilArfaoui** [comment]
Yep, thanks ! Didn’t find the time to handle it yet !

**Comment by michael-callforce** [comment]
> This is quite important, as I currently show hundreds of results, and have resorted to only showing results after 3 letters.

@GMchris Mind if you share your solution? Did you just use the `filterOption` prop?

**Pull request closed without merging**
