### PR TITLE
protect against reading removeEventListener from el if null

### PR DESCRIPTION
**Pull request by eythort**
Causes a crash in react app in some rare cases. Probably a race condition. Seems a fix, checking for el, was added for the mount part, but left out for the unmount

### CODE REVIEW

**Review by JedWatson — APPROVED** [review]

**Comment by Methuselah96** [comment]
Thanks!

**Comment by nifgraup** [comment]
The `if (!el) return;` check would not be needed if `el` was really of type `HTMLElement`.

**Comment by dfiad77pro** [comment]
I think you have to release a minor version with this fix, I have the same problem when I upgrade from react 16--> 17 ( react-select is  included on child npm package),
with a fork with your fix, all work :)

**Comment by Methuselah96** [comment]
@dfiad77pro It would be great if you could provide a reproducible sample of this. Can you make a CodeSandbox showing it not working?

**Comment by dfiad77pro** [comment]
Its currently difficult for me to do that because my code is protected by my company, but i will try to reproduce this on more conventional way (ps : sorry for my english :) )

**Comment by AdDfNet** [comment]
finally i will have not time to reproduce issue on CodeSandbox :( i will make a temp fork on react select for my company and when this commit will be published i will remove my fork (published on private repository).

ps : I can show you the problem with skype/teams private meeting. But i think you will waste time because this fix is good :)

**Comment by AdDfNet** [comment]
I resolve my issue by setting captureMenuScroll to false (instead of true or undefined)

**Pull request merged**
