### PR TITLE
Add clearableValue option for Multi-Select

### LINKED ISSUE #458: Question: Disabling removal of items in multiselect
Is there a way to disable the removal of an individual value in multiselect mode?  I have a use case where a user can select multiple things, but some items are locked in, meaning they cannot be removed from the list.  I'd really need two things here:

1. Disable or hide the "X" when the item is in the list of current values.
2. Apply a different class to a disabled value so that I can style it differently.

### PR DESCRIPTION
**Pull request by slybridges**
Fixes #458

### CODE REVIEW

**Comment by slybridges** [comment]
On this PR I've added a note in the `README` that the `clearableValue` should only be used along with the `clearable` prop set to `false`.

This is because if we want not to clear the options that have `clearableValue=false` when pressing the `Clear All`button, we have to iterate over each `valueArray` all the time which I felt could have some perf issues.

**Comment by slybridges** [comment]
@jedwatson - anything you'd need from me to get this merged ?

**Comment by JedWatson** [comment]
Sorry for the delay @slybridges - this looks great, I'm merging it now.

**Comment by slybridges** [comment]
:+1: @JedWatson.
No worries for the delay, I understand open source can be tough on you sometimes ;)

**Comment by shivamjjha** [comment]
Seems this is removed in latest version of react-select ?
https://codesandbox.io/s/codesandboxer-example-forked-pn5c9c?file=/example.tsx

**Comment by vivekrekhadia** [comment]
> Seems this is removed in latest version of react-select ? https://codesandbox.io/s/codesandboxer-example-forked-pn5c9c?file=/example.tsx

How you solved it then, I am having the same issue.

**Pull request merged**
