### PR TITLE
Fix missing .focus() method in Creatable (#1437)

### PR DESCRIPTION
**Pull request by the-spyke**
Fixes the #1437 by adding `.focus()` instance method to `Creatable`.

### CODE REVIEW

**Comment by mattraykowski** [comment]
@the-spyke , could you repeat this for ```AsyncCreatable``` as well?

**Comment by the-spyke** [comment]
@mattraykowski Sure, I'll push updates tomorrow.

**Comment by the-spyke** [comment]
Can someone help me to understand, why test coverage dropped so dramatically? I've just added 4 lines of code + test for them.

**Comment by chrisgervang** [comment]
I noticed this was missing in the typescript definition as well. When this gets merged I'll update the definition. :D Thanks!

**Comment by Grisu118** [comment]
@JedWatson Is there any change that this get merged in the near future? We need this feature to fulfill our requirements.

**Comment by the-spyke** [comment]
I will add missing typescript definitions tomorrow. But I need someone to help me with code coverage check.

**Comment by the-spyke** [comment]
Oh, typings aren't in this repository.

**Comment by the-spyke** [comment]
Coverage is 93% again. That's weird.

**Comment by JedWatson** [comment]
Thanks @the-spyke! Merging it now.

**Pull request merged**
